//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:27 PM IST 
//


package com.ericsson.tool.asn.lte.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for EllipsoidPointWithAltitudeAndUncertaintyEllipsoidMapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EllipsoidPointWithAltitudeAndUncertaintyEllipsoidMapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="latitudeSign"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="north"/&gt;
 *               &lt;enumeration value="south"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="degreesLatitude"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt"&gt;
 *               &lt;minInclusive value="0"/&gt;
 *               &lt;maxInclusive value="8388607"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="degreesLongitude"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;minInclusive value="-8388608"/&gt;
 *               &lt;maxInclusive value="8388607"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="altitudeDirection"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="height"/&gt;
 *               &lt;enumeration value="depth"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="altitude"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
 *               &lt;minInclusive value="0"/&gt;
 *               &lt;maxInclusive value="32767"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="uncertaintySemiMajor"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte"&gt;
 *               &lt;minInclusive value="0"/&gt;
 *               &lt;maxInclusive value="127"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="uncertaintySemiMinor"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte"&gt;
 *               &lt;minInclusive value="0"/&gt;
 *               &lt;maxInclusive value="127"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="orientationMajorAxis"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte"&gt;
 *               &lt;minInclusive value="0"/&gt;
 *               &lt;maxInclusive value="179"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="uncertaintyAltitude"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte"&gt;
 *               &lt;minInclusive value="0"/&gt;
 *               &lt;maxInclusive value="127"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="confidence"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte"&gt;
 *               &lt;minInclusive value="0"/&gt;
 *               &lt;maxInclusive value="100"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EllipsoidPointWithAltitudeAndUncertaintyEllipsoidMapper", propOrder = {
    "latitudeSign",
    "degreesLatitude",
    "degreesLongitude",
    "altitudeDirection",
    "altitude",
    "uncertaintySemiMajor",
    "uncertaintySemiMinor",
    "orientationMajorAxis",
    "uncertaintyAltitude",
    "confidence"
})
public class EllipsoidPointWithAltitudeAndUncertaintyEllipsoidMapper {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String latitudeSign;
    protected long degreesLatitude;
    protected int degreesLongitude;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String altitudeDirection;
    protected int altitude;
    protected short uncertaintySemiMajor;
    protected short uncertaintySemiMinor;
    protected short orientationMajorAxis;
    protected short uncertaintyAltitude;
    protected short confidence;

    /**
     * Gets the value of the latitudeSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLatitudeSign() {
        return latitudeSign;
    }

    /**
     * Sets the value of the latitudeSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLatitudeSign(String value) {
        this.latitudeSign = value;
    }

    /**
     * Gets the value of the degreesLatitude property.
     * 
     */
    public long getDegreesLatitude() {
        return degreesLatitude;
    }

    /**
     * Sets the value of the degreesLatitude property.
     * 
     */
    public void setDegreesLatitude(long value) {
        this.degreesLatitude = value;
    }

    /**
     * Gets the value of the degreesLongitude property.
     * 
     */
    public int getDegreesLongitude() {
        return degreesLongitude;
    }

    /**
     * Sets the value of the degreesLongitude property.
     * 
     */
    public void setDegreesLongitude(int value) {
        this.degreesLongitude = value;
    }

    /**
     * Gets the value of the altitudeDirection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAltitudeDirection() {
        return altitudeDirection;
    }

    /**
     * Sets the value of the altitudeDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAltitudeDirection(String value) {
        this.altitudeDirection = value;
    }

    /**
     * Gets the value of the altitude property.
     * 
     */
    public int getAltitude() {
        return altitude;
    }

    /**
     * Sets the value of the altitude property.
     * 
     */
    public void setAltitude(int value) {
        this.altitude = value;
    }

    /**
     * Gets the value of the uncertaintySemiMajor property.
     * 
     */
    public short getUncertaintySemiMajor() {
        return uncertaintySemiMajor;
    }

    /**
     * Sets the value of the uncertaintySemiMajor property.
     * 
     */
    public void setUncertaintySemiMajor(short value) {
        this.uncertaintySemiMajor = value;
    }

    /**
     * Gets the value of the uncertaintySemiMinor property.
     * 
     */
    public short getUncertaintySemiMinor() {
        return uncertaintySemiMinor;
    }

    /**
     * Sets the value of the uncertaintySemiMinor property.
     * 
     */
    public void setUncertaintySemiMinor(short value) {
        this.uncertaintySemiMinor = value;
    }

    /**
     * Gets the value of the orientationMajorAxis property.
     * 
     */
    public short getOrientationMajorAxis() {
        return orientationMajorAxis;
    }

    /**
     * Sets the value of the orientationMajorAxis property.
     * 
     */
    public void setOrientationMajorAxis(short value) {
        this.orientationMajorAxis = value;
    }

    /**
     * Gets the value of the uncertaintyAltitude property.
     * 
     */
    public short getUncertaintyAltitude() {
        return uncertaintyAltitude;
    }

    /**
     * Sets the value of the uncertaintyAltitude property.
     * 
     */
    public void setUncertaintyAltitude(short value) {
        this.uncertaintyAltitude = value;
    }

    /**
     * Gets the value of the confidence property.
     * 
     */
    public short getConfidence() {
        return confidence;
    }

    /**
     * Sets the value of the confidence property.
     * 
     */
    public void setConfidence(short value) {
        this.confidence = value;
    }

}
