//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:27 PM IST 
//


package com.ericsson.tool.asn.lte.mapper.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GBR-QosInformationMapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GBR-QosInformationMapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="e-RAB-MaximumBitrateDL" type="{}BitRateMapper"/&gt;
 *         &lt;element name="e-RAB-MaximumBitrateUL" type="{}BitRateMapper"/&gt;
 *         &lt;element name="e-RAB-GuaranteedBitrateDL" type="{}BitRateMapper"/&gt;
 *         &lt;element name="e-RAB-GuaranteedBitrateUL" type="{}BitRateMapper"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GBR-QosInformationMapper", propOrder = {
    "erabMaximumBitrateDL",
    "erabMaximumBitrateUL",
    "erabGuaranteedBitrateDL",
    "erabGuaranteedBitrateUL"
})
public class GBRQosInformationMapper {

    @XmlElement(name = "e-RAB-MaximumBitrateDL", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger erabMaximumBitrateDL;
    @XmlElement(name = "e-RAB-MaximumBitrateUL", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger erabMaximumBitrateUL;
    @XmlElement(name = "e-RAB-GuaranteedBitrateDL", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger erabGuaranteedBitrateDL;
    @XmlElement(name = "e-RAB-GuaranteedBitrateUL", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger erabGuaranteedBitrateUL;

    /**
     * Gets the value of the erabMaximumBitrateDL property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getERABMaximumBitrateDL() {
        return erabMaximumBitrateDL;
    }

    /**
     * Sets the value of the erabMaximumBitrateDL property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setERABMaximumBitrateDL(BigInteger value) {
        this.erabMaximumBitrateDL = value;
    }

    /**
     * Gets the value of the erabMaximumBitrateUL property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getERABMaximumBitrateUL() {
        return erabMaximumBitrateUL;
    }

    /**
     * Sets the value of the erabMaximumBitrateUL property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setERABMaximumBitrateUL(BigInteger value) {
        this.erabMaximumBitrateUL = value;
    }

    /**
     * Gets the value of the erabGuaranteedBitrateDL property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getERABGuaranteedBitrateDL() {
        return erabGuaranteedBitrateDL;
    }

    /**
     * Sets the value of the erabGuaranteedBitrateDL property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setERABGuaranteedBitrateDL(BigInteger value) {
        this.erabGuaranteedBitrateDL = value;
    }

    /**
     * Gets the value of the erabGuaranteedBitrateUL property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getERABGuaranteedBitrateUL() {
        return erabGuaranteedBitrateUL;
    }

    /**
     * Sets the value of the erabGuaranteedBitrateUL property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setERABGuaranteedBitrateUL(BigInteger value) {
        this.erabGuaranteedBitrateUL = value;
    }

}
