//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:27 PM IST 
//


package com.ericsson.tool.asn.lte.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="handoverRequest" type="{}X2HandoverRequestMapper"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "handoverRequest"
})
@XmlRootElement(name = "x2apPduMapper")
public class X2ApPduMapper {

    protected X2HandoverRequestMapper handoverRequest;

    /**
     * Gets the value of the handoverRequest property.
     * 
     * @return
     *     possible object is
     *     {@link X2HandoverRequestMapper }
     *     
     */
    public X2HandoverRequestMapper getHandoverRequest() {
        return handoverRequest;
    }

    /**
     * Sets the value of the handoverRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link X2HandoverRequestMapper }
     *     
     */
    public void setHandoverRequest(X2HandoverRequestMapper value) {
        this.handoverRequest = value;
    }

}
