//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:27 PM IST 
//


package com.ericsson.tool.asn.lte.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for X2ProtocolIE-FieldMapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="X2ProtocolIE-FieldMapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{}ProtocolIE-IDMapper"/&gt;
 *         &lt;element name="criticality" type="{}CriticalityMapper"/&gt;
 *         &lt;element name="value" type="{}X2OpenType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "X2ProtocolIE-FieldMapper", propOrder = {
    "id",
    "criticality",
    "value"
})
@XmlSeeAlso({
    X2ProtocolIESingleContainerMapper.class
})
public class X2ProtocolIEFieldMapper {

    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected ProtocolIEIDMapper id;
    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected CriticalityMapper criticality;
    @XmlElement(required = true)
    protected X2OpenType value;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link ProtocolIEIDMapper }
     *     
     */
    public ProtocolIEIDMapper getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtocolIEIDMapper }
     *     
     */
    public void setId(ProtocolIEIDMapper value) {
        this.id = value;
    }

    /**
     * Gets the value of the criticality property.
     * 
     * @return
     *     possible object is
     *     {@link CriticalityMapper }
     *     
     */
    public CriticalityMapper getCriticality() {
        return criticality;
    }

    /**
     * Sets the value of the criticality property.
     * 
     * @param value
     *     allowed object is
     *     {@link CriticalityMapper }
     *     
     */
    public void setCriticality(CriticalityMapper value) {
        this.criticality = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link X2OpenType }
     *     
     */
    public X2OpenType getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link X2OpenType }
     *     
     */
    public void setValue(X2OpenType value) {
        this.value = value;
    }

}
