//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BandCombinationList-v1630Mapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BandCombinationList-v1630Mapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="65536"&gt;
 *         &lt;element name="BandCombination-v1630" type="{http://www.obj-sys.com/NR-RRC-Definitions}BandCombination-v1630Mapper"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BandCombinationList-v1630Mapper", propOrder = {
    "bandCombinationV1630"
})
public class BandCombinationListV1630Mapper {

    @XmlElement(name = "BandCombination-v1630", required = true)
    protected List<BandCombinationV1630Mapper> bandCombinationV1630;

    /**
     * Gets the value of the bandCombinationV1630 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bandCombinationV1630 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBandCombinationV1630().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BandCombinationV1630Mapper }
     * 
     * 
     */
    public List<BandCombinationV1630Mapper> getBandCombinationV1630() {
        if (bandCombinationV1630 == null) {
            bandCombinationV1630 = new ArrayList<BandCombinationV1630Mapper>();
        }
        return this.bandCombinationV1630;
    }

}
