//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BandCombination-v1580Mapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BandCombination-v1580Mapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="mrdc-Parameters-v1580" type="{http://www.obj-sys.com/NR-RRC-Definitions}MRDC-Parameters-v1580Mapper"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BandCombination-v1580Mapper", propOrder = {
    "mrdcParametersV1580"
})
public class BandCombinationV1580Mapper {

    @XmlElement(name = "mrdc-Parameters-v1580", required = true)
    protected MRDCParametersV1580Mapper mrdcParametersV1580;

    /**
     * Gets the value of the mrdcParametersV1580 property.
     * 
     * @return
     *     possible object is
     *     {@link MRDCParametersV1580Mapper }
     *     
     */
    public MRDCParametersV1580Mapper getMrdcParametersV1580() {
        return mrdcParametersV1580;
    }

    /**
     * Sets the value of the mrdcParametersV1580 property.
     * 
     * @param value
     *     allowed object is
     *     {@link MRDCParametersV1580Mapper }
     *     
     */
    public void setMrdcParametersV1580(MRDCParametersV1580Mapper value) {
        this.mrdcParametersV1580 = value;
    }

}
