//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for BandCombination-v1560Mapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BandCombination-v1560Mapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ne-DC-BC" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ca-ParametersNRDC" type="{http://www.obj-sys.com/NR-RRC-Definitions}CA-ParametersNRDCMapper" minOccurs="0"/&gt;
 *         &lt;element name="ca-ParametersEUTRA-v1560" type="{http://www.obj-sys.com/NR-RRC-Definitions}CA-ParametersEUTRA-v1560Mapper" minOccurs="0"/&gt;
 *         &lt;element name="ca-ParametersNR-v1560" type="{http://www.obj-sys.com/NR-RRC-Definitions}CA-ParametersNR-v1560Mapper" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BandCombination-v1560Mapper", propOrder = {
    "neDCBC",
    "caParametersNRDC",
    "caParametersEUTRAV1560",
    "caParametersNRV1560"
})
public class BandCombinationV1560Mapper {

    @XmlElement(name = "ne-DC-BC")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String neDCBC;
    @XmlElement(name = "ca-ParametersNRDC")
    protected CAParametersNRDCMapper caParametersNRDC;
    @XmlElement(name = "ca-ParametersEUTRA-v1560")
    protected CAParametersEUTRAV1560Mapper caParametersEUTRAV1560;
    @XmlElement(name = "ca-ParametersNR-v1560")
    protected CAParametersNRV1560Mapper caParametersNRV1560;

    /**
     * Gets the value of the neDCBC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNeDCBC() {
        return neDCBC;
    }

    /**
     * Sets the value of the neDCBC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNeDCBC(String value) {
        this.neDCBC = value;
    }

    /**
     * Gets the value of the caParametersNRDC property.
     * 
     * @return
     *     possible object is
     *     {@link CAParametersNRDCMapper }
     *     
     */
    public CAParametersNRDCMapper getCaParametersNRDC() {
        return caParametersNRDC;
    }

    /**
     * Sets the value of the caParametersNRDC property.
     * 
     * @param value
     *     allowed object is
     *     {@link CAParametersNRDCMapper }
     *     
     */
    public void setCaParametersNRDC(CAParametersNRDCMapper value) {
        this.caParametersNRDC = value;
    }

    /**
     * Gets the value of the caParametersEUTRAV1560 property.
     * 
     * @return
     *     possible object is
     *     {@link CAParametersEUTRAV1560Mapper }
     *     
     */
    public CAParametersEUTRAV1560Mapper getCaParametersEUTRAV1560() {
        return caParametersEUTRAV1560;
    }

    /**
     * Sets the value of the caParametersEUTRAV1560 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CAParametersEUTRAV1560Mapper }
     *     
     */
    public void setCaParametersEUTRAV1560(CAParametersEUTRAV1560Mapper value) {
        this.caParametersEUTRAV1560 = value;
    }

    /**
     * Gets the value of the caParametersNRV1560 property.
     * 
     * @return
     *     possible object is
     *     {@link CAParametersNRV1560Mapper }
     *     
     */
    public CAParametersNRV1560Mapper getCaParametersNRV1560() {
        return caParametersNRV1560;
    }

    /**
     * Sets the value of the caParametersNRV1560 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CAParametersNRV1560Mapper }
     *     
     */
    public void setCaParametersNRV1560(CAParametersNRV1560Mapper value) {
        this.caParametersNRV1560 = value;
    }

}
