//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BandCombinationList-UplinkTxSwitch-v1640Mapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BandCombinationList-UplinkTxSwitch-v1640Mapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="65536"&gt;
 *         &lt;element name="BandCombination-UplinkTxSwitch-v1640" type="{http://www.obj-sys.com/NR-RRC-Definitions}BandCombination-UplinkTxSwitch-v1640Mapper"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BandCombinationList-UplinkTxSwitch-v1640Mapper", propOrder = {
    "bandCombinationUplinkTxSwitchV1640"
})
public class BandCombinationListUplinkTxSwitchV1640Mapper {

    @XmlElement(name = "BandCombination-UplinkTxSwitch-v1640", required = true)
    protected List<BandCombinationUplinkTxSwitchV1640Mapper> bandCombinationUplinkTxSwitchV1640;

    /**
     * Gets the value of the bandCombinationUplinkTxSwitchV1640 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bandCombinationUplinkTxSwitchV1640 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBandCombinationUplinkTxSwitchV1640().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BandCombinationUplinkTxSwitchV1640Mapper }
     * 
     * 
     */
    public List<BandCombinationUplinkTxSwitchV1640Mapper> getBandCombinationUplinkTxSwitchV1640() {
        if (bandCombinationUplinkTxSwitchV1640 == null) {
            bandCombinationUplinkTxSwitchV1640 = new ArrayList<BandCombinationUplinkTxSwitchV1640Mapper>();
        }
        return this.bandCombinationUplinkTxSwitchV1640;
    }

}
