//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for BAP-Parameters-r16Mapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BAP-Parameters-r16Mapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="flowControlBH-RLC-ChannelBased-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="flowControlRouting-ID-Based-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BAP-Parameters-r16Mapper", propOrder = {
    "flowControlBHRLCChannelBasedR16",
    "flowControlRoutingIDBasedR16"
})
public class BAPParametersR16Mapper {

    @XmlElement(name = "flowControlBH-RLC-ChannelBased-r16")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String flowControlBHRLCChannelBasedR16;
    @XmlElement(name = "flowControlRouting-ID-Based-r16")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String flowControlRoutingIDBasedR16;

    /**
     * Gets the value of the flowControlBHRLCChannelBasedR16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlowControlBHRLCChannelBasedR16() {
        return flowControlBHRLCChannelBasedR16;
    }

    /**
     * Sets the value of the flowControlBHRLCChannelBasedR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlowControlBHRLCChannelBasedR16(String value) {
        this.flowControlBHRLCChannelBasedR16 = value;
    }

    /**
     * Gets the value of the flowControlRoutingIDBasedR16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlowControlRoutingIDBasedR16() {
        return flowControlRoutingIDBasedR16;
    }

    /**
     * Sets the value of the flowControlRoutingIDBasedR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlowControlRoutingIDBasedR16(String value) {
        this.flowControlRoutingIDBasedR16 = value;
    }

}
