//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CA-ParametersNRDC-v1630Mapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CA-ParametersNRDC-v1630Mapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ca-ParametersNR-ForDC-v1610" type="{http://www.obj-sys.com/NR-RRC-Definitions}CA-ParametersNR-v1610Mapper" minOccurs="0"/&gt;
 *         &lt;element name="ca-ParametersNR-ForDC-v1630" type="{http://www.obj-sys.com/NR-RRC-Definitions}CA-ParametersNR-v1630Mapper" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CA-ParametersNRDC-v1630Mapper", propOrder = {
    "caParametersNRForDCV1610",
    "caParametersNRForDCV1630"
})
public class CAParametersNRDCV1630Mapper {

    @XmlElement(name = "ca-ParametersNR-ForDC-v1610")
    protected CAParametersNRV1610Mapper caParametersNRForDCV1610;
    @XmlElement(name = "ca-ParametersNR-ForDC-v1630")
    protected CAParametersNRV1630Mapper caParametersNRForDCV1630;

    /**
     * Gets the value of the caParametersNRForDCV1610 property.
     * 
     * @return
     *     possible object is
     *     {@link CAParametersNRV1610Mapper }
     *     
     */
    public CAParametersNRV1610Mapper getCaParametersNRForDCV1610() {
        return caParametersNRForDCV1610;
    }

    /**
     * Sets the value of the caParametersNRForDCV1610 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CAParametersNRV1610Mapper }
     *     
     */
    public void setCaParametersNRForDCV1610(CAParametersNRV1610Mapper value) {
        this.caParametersNRForDCV1610 = value;
    }

    /**
     * Gets the value of the caParametersNRForDCV1630 property.
     * 
     * @return
     *     possible object is
     *     {@link CAParametersNRV1630Mapper }
     *     
     */
    public CAParametersNRV1630Mapper getCaParametersNRForDCV1630() {
        return caParametersNRForDCV1630;
    }

    /**
     * Sets the value of the caParametersNRForDCV1630 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CAParametersNRV1630Mapper }
     *     
     */
    public void setCaParametersNRForDCV1630(CAParametersNRV1630Mapper value) {
        this.caParametersNRForDCV1630 = value;
    }

}
