//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CellAccessRelatedInfo-EUTRA-EPCMapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CellAccessRelatedInfo-EUTRA-EPCMapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="plmn-IdentityList-eutra-epc" type="{}PLMN-IdentityList-EUTRA-EPCMapper"/&gt;
 *         &lt;element name="trackingAreaCode-eutra-epc"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.obj-sys.com/v1.0/XMLSchema}BitString"&gt;
 *               &lt;length value="16"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="cellIdentity-eutra-epc"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.obj-sys.com/v1.0/XMLSchema}BitString"&gt;
 *               &lt;length value="28"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CellAccessRelatedInfo-EUTRA-EPCMapper", namespace = "", propOrder = {
    "plmnIdentityListEutraEpc",
    "trackingAreaCodeEutraEpc",
    "cellIdentityEutraEpc"
})
public class CellAccessRelatedInfoEUTRAEPCMapper {

    @XmlElement(name = "plmn-IdentityList-eutra-epc", required = true)
    protected PLMNIdentityListEUTRAEPCMapper plmnIdentityListEutraEpc;
    @XmlElement(name = "trackingAreaCode-eutra-epc", required = true)
    protected String trackingAreaCodeEutraEpc;
    @XmlElement(name = "cellIdentity-eutra-epc", required = true)
    protected String cellIdentityEutraEpc;

    /**
     * Gets the value of the plmnIdentityListEutraEpc property.
     * 
     * @return
     *     possible object is
     *     {@link PLMNIdentityListEUTRAEPCMapper }
     *     
     */
    public PLMNIdentityListEUTRAEPCMapper getPlmnIdentityListEutraEpc() {
        return plmnIdentityListEutraEpc;
    }

    /**
     * Sets the value of the plmnIdentityListEutraEpc property.
     * 
     * @param value
     *     allowed object is
     *     {@link PLMNIdentityListEUTRAEPCMapper }
     *     
     */
    public void setPlmnIdentityListEutraEpc(PLMNIdentityListEUTRAEPCMapper value) {
        this.plmnIdentityListEutraEpc = value;
    }

    /**
     * Gets the value of the trackingAreaCodeEutraEpc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackingAreaCodeEutraEpc() {
        return trackingAreaCodeEutraEpc;
    }

    /**
     * Sets the value of the trackingAreaCodeEutraEpc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackingAreaCodeEutraEpc(String value) {
        this.trackingAreaCodeEutraEpc = value;
    }

    /**
     * Gets the value of the cellIdentityEutraEpc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCellIdentityEutraEpc() {
        return cellIdentityEutraEpc;
    }

    /**
     * Sets the value of the cellIdentityEutraEpc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCellIdentityEutraEpc(String value) {
        this.cellIdentityEutraEpc = value;
    }

}
