//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for CGI-InfoEUTRAMapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CGI-InfoEUTRAMapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cgi-info-EPC" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="cgi-info-EPC-legacy" type="{}CellAccessRelatedInfo-EUTRA-EPCMapper"/&gt;
 *                   &lt;element name="cgi-info-EPC-list" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence maxOccurs="12"&gt;
 *                             &lt;element name="CellAccessRelatedInfo-EUTRA-EPC" type="{}CellAccessRelatedInfo-EUTRA-EPCMapper"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="cgi-info-5GC" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence maxOccurs="12"&gt;
 *                   &lt;element name="CellAccessRelatedInfo-EUTRA-5GC" type="{}CellAccessRelatedInfo-EUTRA-5GCMapper"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="freqBandIndicator" type="{}FreqBandIndicatorEUTRAMapper"/&gt;
 *         &lt;element name="multiBandInfoList" type="{}MultiBandInfoListEUTRAMapper" minOccurs="0"/&gt;
 *         &lt;element name="freqBandIndicatorPriority" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="true"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CGI-InfoEUTRAMapper", namespace = "", propOrder = {
    "cgiInfoEPC",
    "cgiInfo5GC",
    "freqBandIndicator",
    "multiBandInfoList",
    "freqBandIndicatorPriority"
})
public class CGIInfoEUTRAMapper {

    @XmlElement(name = "cgi-info-EPC")
    protected CGIInfoEUTRAMapper.CgiInfoEPC cgiInfoEPC;
    @XmlElement(name = "cgi-info-5GC")
    protected CGIInfoEUTRAMapper.CgiInfo5GC cgiInfo5GC;
    @XmlSchemaType(name = "unsignedShort")
    protected int freqBandIndicator;
    @XmlList
    @XmlElement(type = Integer.class)
    protected List<Integer> multiBandInfoList;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String freqBandIndicatorPriority;

    /**
     * Gets the value of the cgiInfoEPC property.
     * 
     * @return
     *     possible object is
     *     {@link CGIInfoEUTRAMapper.CgiInfoEPC }
     *     
     */
    public CGIInfoEUTRAMapper.CgiInfoEPC getCgiInfoEPC() {
        return cgiInfoEPC;
    }

    /**
     * Sets the value of the cgiInfoEPC property.
     * 
     * @param value
     *     allowed object is
     *     {@link CGIInfoEUTRAMapper.CgiInfoEPC }
     *     
     */
    public void setCgiInfoEPC(CGIInfoEUTRAMapper.CgiInfoEPC value) {
        this.cgiInfoEPC = value;
    }

    /**
     * Gets the value of the cgiInfo5GC property.
     * 
     * @return
     *     possible object is
     *     {@link CGIInfoEUTRAMapper.CgiInfo5GC }
     *     
     */
    public CGIInfoEUTRAMapper.CgiInfo5GC getCgiInfo5GC() {
        return cgiInfo5GC;
    }

    /**
     * Sets the value of the cgiInfo5GC property.
     * 
     * @param value
     *     allowed object is
     *     {@link CGIInfoEUTRAMapper.CgiInfo5GC }
     *     
     */
    public void setCgiInfo5GC(CGIInfoEUTRAMapper.CgiInfo5GC value) {
        this.cgiInfo5GC = value;
    }

    /**
     * Gets the value of the freqBandIndicator property.
     * 
     */
    public int getFreqBandIndicator() {
        return freqBandIndicator;
    }

    /**
     * Sets the value of the freqBandIndicator property.
     * 
     */
    public void setFreqBandIndicator(int value) {
        this.freqBandIndicator = value;
    }

    /**
     * Gets the value of the multiBandInfoList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the multiBandInfoList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMultiBandInfoList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getMultiBandInfoList() {
        if (multiBandInfoList == null) {
            multiBandInfoList = new ArrayList<Integer>();
        }
        return this.multiBandInfoList;
    }

    /**
     * Gets the value of the freqBandIndicatorPriority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreqBandIndicatorPriority() {
        return freqBandIndicatorPriority;
    }

    /**
     * Sets the value of the freqBandIndicatorPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreqBandIndicatorPriority(String value) {
        this.freqBandIndicatorPriority = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence maxOccurs="12"&gt;
     *         &lt;element name="CellAccessRelatedInfo-EUTRA-5GC" type="{}CellAccessRelatedInfo-EUTRA-5GCMapper"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cellAccessRelatedInfoEUTRA5GC"
    })
    public static class CgiInfo5GC {

        @XmlElement(name = "CellAccessRelatedInfo-EUTRA-5GC", namespace = "", required = true)
        protected List<CellAccessRelatedInfoEUTRA5GCMapper> cellAccessRelatedInfoEUTRA5GC;

        /**
         * Gets the value of the cellAccessRelatedInfoEUTRA5GC property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the cellAccessRelatedInfoEUTRA5GC property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCellAccessRelatedInfoEUTRA5GC().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CellAccessRelatedInfoEUTRA5GCMapper }
         * 
         * 
         */
        public List<CellAccessRelatedInfoEUTRA5GCMapper> getCellAccessRelatedInfoEUTRA5GC() {
            if (cellAccessRelatedInfoEUTRA5GC == null) {
                cellAccessRelatedInfoEUTRA5GC = new ArrayList<CellAccessRelatedInfoEUTRA5GCMapper>();
            }
            return this.cellAccessRelatedInfoEUTRA5GC;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="cgi-info-EPC-legacy" type="{}CellAccessRelatedInfo-EUTRA-EPCMapper"/&gt;
     *         &lt;element name="cgi-info-EPC-list" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence maxOccurs="12"&gt;
     *                   &lt;element name="CellAccessRelatedInfo-EUTRA-EPC" type="{}CellAccessRelatedInfo-EUTRA-EPCMapper"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cgiInfoEPCLegacy",
        "cgiInfoEPCList"
    })
    public static class CgiInfoEPC {

        @XmlElement(name = "cgi-info-EPC-legacy", namespace = "", required = true)
        protected CellAccessRelatedInfoEUTRAEPCMapper cgiInfoEPCLegacy;
        @XmlElement(name = "cgi-info-EPC-list", namespace = "")
        protected CGIInfoEUTRAMapper.CgiInfoEPC.CgiInfoEPCList cgiInfoEPCList;

        /**
         * Gets the value of the cgiInfoEPCLegacy property.
         * 
         * @return
         *     possible object is
         *     {@link CellAccessRelatedInfoEUTRAEPCMapper }
         *     
         */
        public CellAccessRelatedInfoEUTRAEPCMapper getCgiInfoEPCLegacy() {
            return cgiInfoEPCLegacy;
        }

        /**
         * Sets the value of the cgiInfoEPCLegacy property.
         * 
         * @param value
         *     allowed object is
         *     {@link CellAccessRelatedInfoEUTRAEPCMapper }
         *     
         */
        public void setCgiInfoEPCLegacy(CellAccessRelatedInfoEUTRAEPCMapper value) {
            this.cgiInfoEPCLegacy = value;
        }

        /**
         * Gets the value of the cgiInfoEPCList property.
         * 
         * @return
         *     possible object is
         *     {@link CGIInfoEUTRAMapper.CgiInfoEPC.CgiInfoEPCList }
         *     
         */
        public CGIInfoEUTRAMapper.CgiInfoEPC.CgiInfoEPCList getCgiInfoEPCList() {
            return cgiInfoEPCList;
        }

        /**
         * Sets the value of the cgiInfoEPCList property.
         * 
         * @param value
         *     allowed object is
         *     {@link CGIInfoEUTRAMapper.CgiInfoEPC.CgiInfoEPCList }
         *     
         */
        public void setCgiInfoEPCList(CGIInfoEUTRAMapper.CgiInfoEPC.CgiInfoEPCList value) {
            this.cgiInfoEPCList = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence maxOccurs="12"&gt;
         *         &lt;element name="CellAccessRelatedInfo-EUTRA-EPC" type="{}CellAccessRelatedInfo-EUTRA-EPCMapper"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cellAccessRelatedInfoEUTRAEPC"
        })
        public static class CgiInfoEPCList {

            @XmlElement(name = "CellAccessRelatedInfo-EUTRA-EPC", namespace = "", required = true)
            protected List<CellAccessRelatedInfoEUTRAEPCMapper> cellAccessRelatedInfoEUTRAEPC;

            /**
             * Gets the value of the cellAccessRelatedInfoEUTRAEPC property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the cellAccessRelatedInfoEUTRAEPC property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCellAccessRelatedInfoEUTRAEPC().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CellAccessRelatedInfoEUTRAEPCMapper }
             * 
             * 
             */
            public List<CellAccessRelatedInfoEUTRAEPCMapper> getCellAccessRelatedInfoEUTRAEPC() {
                if (cellAccessRelatedInfoEUTRAEPC == null) {
                    cellAccessRelatedInfoEUTRAEPC = new ArrayList<CellAccessRelatedInfoEUTRAEPCMapper>();
                }
                return this.cellAccessRelatedInfoEUTRAEPC;
            }

        }

    }

}
