//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CodebookComboParametersAddition-r16Mapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CodebookComboParametersAddition-r16Mapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="type1SP-Type2-null-r16" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction&gt;
 *                         &lt;simpleType&gt;
 *                           &lt;list&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
 *                                 &lt;minInclusive value="0"/&gt;
 *                                 &lt;maxInclusive value="511"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/list&gt;
 *                         &lt;/simpleType&gt;
 *                         &lt;minLength value="1"/&gt;
 *                         &lt;maxLength value="16"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="type1SP-Type2PS-null-r16" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction&gt;
 *                         &lt;simpleType&gt;
 *                           &lt;list&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
 *                                 &lt;minInclusive value="0"/&gt;
 *                                 &lt;maxInclusive value="511"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/list&gt;
 *                         &lt;/simpleType&gt;
 *                         &lt;minLength value="1"/&gt;
 *                         &lt;maxLength value="16"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="type1SP-eType2R1-null-r16" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction&gt;
 *                         &lt;simpleType&gt;
 *                           &lt;list&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
 *                                 &lt;minInclusive value="0"/&gt;
 *                                 &lt;maxInclusive value="511"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/list&gt;
 *                         &lt;/simpleType&gt;
 *                         &lt;minLength value="1"/&gt;
 *                         &lt;maxLength value="16"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="type1SP-eType2R2-null-r16" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction&gt;
 *                         &lt;simpleType&gt;
 *                           &lt;list&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
 *                                 &lt;minInclusive value="0"/&gt;
 *                                 &lt;maxInclusive value="511"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/list&gt;
 *                         &lt;/simpleType&gt;
 *                         &lt;minLength value="1"/&gt;
 *                         &lt;maxLength value="16"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="type1SP-eType2R1PS-null-r16" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction&gt;
 *                         &lt;simpleType&gt;
 *                           &lt;list&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
 *                                 &lt;minInclusive value="0"/&gt;
 *                                 &lt;maxInclusive value="511"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/list&gt;
 *                         &lt;/simpleType&gt;
 *                         &lt;minLength value="1"/&gt;
 *                         &lt;maxLength value="16"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="type1SP-eType2R2PS-null-r16" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction&gt;
 *                         &lt;simpleType&gt;
 *                           &lt;list&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
 *                                 &lt;minInclusive value="0"/&gt;
 *                                 &lt;maxInclusive value="511"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/list&gt;
 *                         &lt;/simpleType&gt;
 *                         &lt;minLength value="1"/&gt;
 *                         &lt;maxLength value="16"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="type1SP-Type2-Type2PS-r16" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction&gt;
 *                         &lt;simpleType&gt;
 *                           &lt;list&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
 *                                 &lt;minInclusive value="0"/&gt;
 *                                 &lt;maxInclusive value="511"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/list&gt;
 *                         &lt;/simpleType&gt;
 *                         &lt;minLength value="1"/&gt;
 *                         &lt;maxLength value="16"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="type1MP-Type2-null-r16" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction&gt;
 *                         &lt;simpleType&gt;
 *                           &lt;list&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
 *                                 &lt;minInclusive value="0"/&gt;
 *                                 &lt;maxInclusive value="511"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/list&gt;
 *                         &lt;/simpleType&gt;
 *                         &lt;minLength value="1"/&gt;
 *                         &lt;maxLength value="16"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="type1MP-Type2PS-null-r16" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction&gt;
 *                         &lt;simpleType&gt;
 *                           &lt;list&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
 *                                 &lt;minInclusive value="0"/&gt;
 *                                 &lt;maxInclusive value="511"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/list&gt;
 *                         &lt;/simpleType&gt;
 *                         &lt;minLength value="1"/&gt;
 *                         &lt;maxLength value="16"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="type1MP-eType2R1-null-r16" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction&gt;
 *                         &lt;simpleType&gt;
 *                           &lt;list&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
 *                                 &lt;minInclusive value="0"/&gt;
 *                                 &lt;maxInclusive value="511"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/list&gt;
 *                         &lt;/simpleType&gt;
 *                         &lt;minLength value="1"/&gt;
 *                         &lt;maxLength value="16"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="type1MP-eType2R2-null-r16" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction&gt;
 *                         &lt;simpleType&gt;
 *                           &lt;list&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
 *                                 &lt;minInclusive value="0"/&gt;
 *                                 &lt;maxInclusive value="511"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/list&gt;
 *                         &lt;/simpleType&gt;
 *                         &lt;minLength value="1"/&gt;
 *                         &lt;maxLength value="16"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="type1MP-eType2R1PS-null-r16" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction&gt;
 *                         &lt;simpleType&gt;
 *                           &lt;list&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
 *                                 &lt;minInclusive value="0"/&gt;
 *                                 &lt;maxInclusive value="511"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/list&gt;
 *                         &lt;/simpleType&gt;
 *                         &lt;minLength value="1"/&gt;
 *                         &lt;maxLength value="16"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="type1MP-eType2R2PS-null-r16" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction&gt;
 *                         &lt;simpleType&gt;
 *                           &lt;list&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
 *                                 &lt;minInclusive value="0"/&gt;
 *                                 &lt;maxInclusive value="511"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/list&gt;
 *                         &lt;/simpleType&gt;
 *                         &lt;minLength value="1"/&gt;
 *                         &lt;maxLength value="16"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="type1MP-Type2-Type2PS-r16" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction&gt;
 *                         &lt;simpleType&gt;
 *                           &lt;list&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
 *                                 &lt;minInclusive value="0"/&gt;
 *                                 &lt;maxInclusive value="511"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/list&gt;
 *                         &lt;/simpleType&gt;
 *                         &lt;minLength value="1"/&gt;
 *                         &lt;maxLength value="16"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CodebookComboParametersAddition-r16Mapper", propOrder = {
    "type1SPType2NullR16",
    "type1SPType2PSNullR16",
    "type1SPEType2R1NullR16",
    "type1SPEType2R2NullR16",
    "type1SPEType2R1PSNullR16",
    "type1SPEType2R2PSNullR16",
    "type1SPType2Type2PSR16",
    "type1MPType2NullR16",
    "type1MPType2PSNullR16",
    "type1MPEType2R1NullR16",
    "type1MPEType2R2NullR16",
    "type1MPEType2R1PSNullR16",
    "type1MPEType2R2PSNullR16",
    "type1MPType2Type2PSR16"
})
public class CodebookComboParametersAdditionR16Mapper {

    @XmlElement(name = "type1SP-Type2-null-r16")
    protected CodebookComboParametersAdditionR16Mapper.Type1SPType2NullR16 type1SPType2NullR16;
    @XmlElement(name = "type1SP-Type2PS-null-r16")
    protected CodebookComboParametersAdditionR16Mapper.Type1SPType2PSNullR16 type1SPType2PSNullR16;
    @XmlElement(name = "type1SP-eType2R1-null-r16")
    protected CodebookComboParametersAdditionR16Mapper.Type1SPEType2R1NullR16 type1SPEType2R1NullR16;
    @XmlElement(name = "type1SP-eType2R2-null-r16")
    protected CodebookComboParametersAdditionR16Mapper.Type1SPEType2R2NullR16 type1SPEType2R2NullR16;
    @XmlElement(name = "type1SP-eType2R1PS-null-r16")
    protected CodebookComboParametersAdditionR16Mapper.Type1SPEType2R1PSNullR16 type1SPEType2R1PSNullR16;
    @XmlElement(name = "type1SP-eType2R2PS-null-r16")
    protected CodebookComboParametersAdditionR16Mapper.Type1SPEType2R2PSNullR16 type1SPEType2R2PSNullR16;
    @XmlElement(name = "type1SP-Type2-Type2PS-r16")
    protected CodebookComboParametersAdditionR16Mapper.Type1SPType2Type2PSR16 type1SPType2Type2PSR16;
    @XmlElement(name = "type1MP-Type2-null-r16")
    protected CodebookComboParametersAdditionR16Mapper.Type1MPType2NullR16 type1MPType2NullR16;
    @XmlElement(name = "type1MP-Type2PS-null-r16")
    protected CodebookComboParametersAdditionR16Mapper.Type1MPType2PSNullR16 type1MPType2PSNullR16;
    @XmlElement(name = "type1MP-eType2R1-null-r16")
    protected CodebookComboParametersAdditionR16Mapper.Type1MPEType2R1NullR16 type1MPEType2R1NullR16;
    @XmlElement(name = "type1MP-eType2R2-null-r16")
    protected CodebookComboParametersAdditionR16Mapper.Type1MPEType2R2NullR16 type1MPEType2R2NullR16;
    @XmlElement(name = "type1MP-eType2R1PS-null-r16")
    protected CodebookComboParametersAdditionR16Mapper.Type1MPEType2R1PSNullR16 type1MPEType2R1PSNullR16;
    @XmlElement(name = "type1MP-eType2R2PS-null-r16")
    protected CodebookComboParametersAdditionR16Mapper.Type1MPEType2R2PSNullR16 type1MPEType2R2PSNullR16;
    @XmlElement(name = "type1MP-Type2-Type2PS-r16")
    protected CodebookComboParametersAdditionR16Mapper.Type1MPType2Type2PSR16 type1MPType2Type2PSR16;

    /**
     * Gets the value of the type1SPType2NullR16 property.
     * 
     * @return
     *     possible object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1SPType2NullR16 }
     *     
     */
    public CodebookComboParametersAdditionR16Mapper.Type1SPType2NullR16 getType1SPType2NullR16() {
        return type1SPType2NullR16;
    }

    /**
     * Sets the value of the type1SPType2NullR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1SPType2NullR16 }
     *     
     */
    public void setType1SPType2NullR16(CodebookComboParametersAdditionR16Mapper.Type1SPType2NullR16 value) {
        this.type1SPType2NullR16 = value;
    }

    /**
     * Gets the value of the type1SPType2PSNullR16 property.
     * 
     * @return
     *     possible object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1SPType2PSNullR16 }
     *     
     */
    public CodebookComboParametersAdditionR16Mapper.Type1SPType2PSNullR16 getType1SPType2PSNullR16() {
        return type1SPType2PSNullR16;
    }

    /**
     * Sets the value of the type1SPType2PSNullR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1SPType2PSNullR16 }
     *     
     */
    public void setType1SPType2PSNullR16(CodebookComboParametersAdditionR16Mapper.Type1SPType2PSNullR16 value) {
        this.type1SPType2PSNullR16 = value;
    }

    /**
     * Gets the value of the type1SPEType2R1NullR16 property.
     * 
     * @return
     *     possible object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1SPEType2R1NullR16 }
     *     
     */
    public CodebookComboParametersAdditionR16Mapper.Type1SPEType2R1NullR16 getType1SPEType2R1NullR16() {
        return type1SPEType2R1NullR16;
    }

    /**
     * Sets the value of the type1SPEType2R1NullR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1SPEType2R1NullR16 }
     *     
     */
    public void setType1SPEType2R1NullR16(CodebookComboParametersAdditionR16Mapper.Type1SPEType2R1NullR16 value) {
        this.type1SPEType2R1NullR16 = value;
    }

    /**
     * Gets the value of the type1SPEType2R2NullR16 property.
     * 
     * @return
     *     possible object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1SPEType2R2NullR16 }
     *     
     */
    public CodebookComboParametersAdditionR16Mapper.Type1SPEType2R2NullR16 getType1SPEType2R2NullR16() {
        return type1SPEType2R2NullR16;
    }

    /**
     * Sets the value of the type1SPEType2R2NullR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1SPEType2R2NullR16 }
     *     
     */
    public void setType1SPEType2R2NullR16(CodebookComboParametersAdditionR16Mapper.Type1SPEType2R2NullR16 value) {
        this.type1SPEType2R2NullR16 = value;
    }

    /**
     * Gets the value of the type1SPEType2R1PSNullR16 property.
     * 
     * @return
     *     possible object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1SPEType2R1PSNullR16 }
     *     
     */
    public CodebookComboParametersAdditionR16Mapper.Type1SPEType2R1PSNullR16 getType1SPEType2R1PSNullR16() {
        return type1SPEType2R1PSNullR16;
    }

    /**
     * Sets the value of the type1SPEType2R1PSNullR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1SPEType2R1PSNullR16 }
     *     
     */
    public void setType1SPEType2R1PSNullR16(CodebookComboParametersAdditionR16Mapper.Type1SPEType2R1PSNullR16 value) {
        this.type1SPEType2R1PSNullR16 = value;
    }

    /**
     * Gets the value of the type1SPEType2R2PSNullR16 property.
     * 
     * @return
     *     possible object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1SPEType2R2PSNullR16 }
     *     
     */
    public CodebookComboParametersAdditionR16Mapper.Type1SPEType2R2PSNullR16 getType1SPEType2R2PSNullR16() {
        return type1SPEType2R2PSNullR16;
    }

    /**
     * Sets the value of the type1SPEType2R2PSNullR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1SPEType2R2PSNullR16 }
     *     
     */
    public void setType1SPEType2R2PSNullR16(CodebookComboParametersAdditionR16Mapper.Type1SPEType2R2PSNullR16 value) {
        this.type1SPEType2R2PSNullR16 = value;
    }

    /**
     * Gets the value of the type1SPType2Type2PSR16 property.
     * 
     * @return
     *     possible object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1SPType2Type2PSR16 }
     *     
     */
    public CodebookComboParametersAdditionR16Mapper.Type1SPType2Type2PSR16 getType1SPType2Type2PSR16() {
        return type1SPType2Type2PSR16;
    }

    /**
     * Sets the value of the type1SPType2Type2PSR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1SPType2Type2PSR16 }
     *     
     */
    public void setType1SPType2Type2PSR16(CodebookComboParametersAdditionR16Mapper.Type1SPType2Type2PSR16 value) {
        this.type1SPType2Type2PSR16 = value;
    }

    /**
     * Gets the value of the type1MPType2NullR16 property.
     * 
     * @return
     *     possible object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1MPType2NullR16 }
     *     
     */
    public CodebookComboParametersAdditionR16Mapper.Type1MPType2NullR16 getType1MPType2NullR16() {
        return type1MPType2NullR16;
    }

    /**
     * Sets the value of the type1MPType2NullR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1MPType2NullR16 }
     *     
     */
    public void setType1MPType2NullR16(CodebookComboParametersAdditionR16Mapper.Type1MPType2NullR16 value) {
        this.type1MPType2NullR16 = value;
    }

    /**
     * Gets the value of the type1MPType2PSNullR16 property.
     * 
     * @return
     *     possible object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1MPType2PSNullR16 }
     *     
     */
    public CodebookComboParametersAdditionR16Mapper.Type1MPType2PSNullR16 getType1MPType2PSNullR16() {
        return type1MPType2PSNullR16;
    }

    /**
     * Sets the value of the type1MPType2PSNullR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1MPType2PSNullR16 }
     *     
     */
    public void setType1MPType2PSNullR16(CodebookComboParametersAdditionR16Mapper.Type1MPType2PSNullR16 value) {
        this.type1MPType2PSNullR16 = value;
    }

    /**
     * Gets the value of the type1MPEType2R1NullR16 property.
     * 
     * @return
     *     possible object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1MPEType2R1NullR16 }
     *     
     */
    public CodebookComboParametersAdditionR16Mapper.Type1MPEType2R1NullR16 getType1MPEType2R1NullR16() {
        return type1MPEType2R1NullR16;
    }

    /**
     * Sets the value of the type1MPEType2R1NullR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1MPEType2R1NullR16 }
     *     
     */
    public void setType1MPEType2R1NullR16(CodebookComboParametersAdditionR16Mapper.Type1MPEType2R1NullR16 value) {
        this.type1MPEType2R1NullR16 = value;
    }

    /**
     * Gets the value of the type1MPEType2R2NullR16 property.
     * 
     * @return
     *     possible object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1MPEType2R2NullR16 }
     *     
     */
    public CodebookComboParametersAdditionR16Mapper.Type1MPEType2R2NullR16 getType1MPEType2R2NullR16() {
        return type1MPEType2R2NullR16;
    }

    /**
     * Sets the value of the type1MPEType2R2NullR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1MPEType2R2NullR16 }
     *     
     */
    public void setType1MPEType2R2NullR16(CodebookComboParametersAdditionR16Mapper.Type1MPEType2R2NullR16 value) {
        this.type1MPEType2R2NullR16 = value;
    }

    /**
     * Gets the value of the type1MPEType2R1PSNullR16 property.
     * 
     * @return
     *     possible object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1MPEType2R1PSNullR16 }
     *     
     */
    public CodebookComboParametersAdditionR16Mapper.Type1MPEType2R1PSNullR16 getType1MPEType2R1PSNullR16() {
        return type1MPEType2R1PSNullR16;
    }

    /**
     * Sets the value of the type1MPEType2R1PSNullR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1MPEType2R1PSNullR16 }
     *     
     */
    public void setType1MPEType2R1PSNullR16(CodebookComboParametersAdditionR16Mapper.Type1MPEType2R1PSNullR16 value) {
        this.type1MPEType2R1PSNullR16 = value;
    }

    /**
     * Gets the value of the type1MPEType2R2PSNullR16 property.
     * 
     * @return
     *     possible object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1MPEType2R2PSNullR16 }
     *     
     */
    public CodebookComboParametersAdditionR16Mapper.Type1MPEType2R2PSNullR16 getType1MPEType2R2PSNullR16() {
        return type1MPEType2R2PSNullR16;
    }

    /**
     * Sets the value of the type1MPEType2R2PSNullR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1MPEType2R2PSNullR16 }
     *     
     */
    public void setType1MPEType2R2PSNullR16(CodebookComboParametersAdditionR16Mapper.Type1MPEType2R2PSNullR16 value) {
        this.type1MPEType2R2PSNullR16 = value;
    }

    /**
     * Gets the value of the type1MPType2Type2PSR16 property.
     * 
     * @return
     *     possible object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1MPType2Type2PSR16 }
     *     
     */
    public CodebookComboParametersAdditionR16Mapper.Type1MPType2Type2PSR16 getType1MPType2Type2PSR16() {
        return type1MPType2Type2PSR16;
    }

    /**
     * Sets the value of the type1MPType2Type2PSR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodebookComboParametersAdditionR16Mapper.Type1MPType2Type2PSR16 }
     *     
     */
    public void setType1MPType2Type2PSR16(CodebookComboParametersAdditionR16Mapper.Type1MPType2Type2PSR16 value) {
        this.type1MPType2Type2PSR16 = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction&gt;
     *               &lt;simpleType&gt;
     *                 &lt;list&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
     *                       &lt;minInclusive value="0"/&gt;
     *                       &lt;maxInclusive value="511"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/list&gt;
     *               &lt;/simpleType&gt;
     *               &lt;minLength value="1"/&gt;
     *               &lt;maxLength value="16"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "supportedCSIRSResourceListAddR16"
    })
    public static class Type1MPEType2R1NullR16 {

        @XmlList
        @XmlElement(name = "supportedCSI-RS-ResourceListAdd-r16", type = Integer.class)
        protected List<Integer> supportedCSIRSResourceListAddR16;

        /**
         * Gets the value of the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSupportedCSIRSResourceListAddR16().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getSupportedCSIRSResourceListAddR16() {
            if (supportedCSIRSResourceListAddR16 == null) {
                supportedCSIRSResourceListAddR16 = new ArrayList<Integer>();
            }
            return this.supportedCSIRSResourceListAddR16;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction&gt;
     *               &lt;simpleType&gt;
     *                 &lt;list&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
     *                       &lt;minInclusive value="0"/&gt;
     *                       &lt;maxInclusive value="511"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/list&gt;
     *               &lt;/simpleType&gt;
     *               &lt;minLength value="1"/&gt;
     *               &lt;maxLength value="16"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "supportedCSIRSResourceListAddR16"
    })
    public static class Type1MPEType2R1PSNullR16 {

        @XmlList
        @XmlElement(name = "supportedCSI-RS-ResourceListAdd-r16", type = Integer.class)
        protected List<Integer> supportedCSIRSResourceListAddR16;

        /**
         * Gets the value of the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSupportedCSIRSResourceListAddR16().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getSupportedCSIRSResourceListAddR16() {
            if (supportedCSIRSResourceListAddR16 == null) {
                supportedCSIRSResourceListAddR16 = new ArrayList<Integer>();
            }
            return this.supportedCSIRSResourceListAddR16;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction&gt;
     *               &lt;simpleType&gt;
     *                 &lt;list&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
     *                       &lt;minInclusive value="0"/&gt;
     *                       &lt;maxInclusive value="511"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/list&gt;
     *               &lt;/simpleType&gt;
     *               &lt;minLength value="1"/&gt;
     *               &lt;maxLength value="16"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "supportedCSIRSResourceListAddR16"
    })
    public static class Type1MPEType2R2NullR16 {

        @XmlList
        @XmlElement(name = "supportedCSI-RS-ResourceListAdd-r16", type = Integer.class)
        protected List<Integer> supportedCSIRSResourceListAddR16;

        /**
         * Gets the value of the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSupportedCSIRSResourceListAddR16().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getSupportedCSIRSResourceListAddR16() {
            if (supportedCSIRSResourceListAddR16 == null) {
                supportedCSIRSResourceListAddR16 = new ArrayList<Integer>();
            }
            return this.supportedCSIRSResourceListAddR16;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction&gt;
     *               &lt;simpleType&gt;
     *                 &lt;list&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
     *                       &lt;minInclusive value="0"/&gt;
     *                       &lt;maxInclusive value="511"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/list&gt;
     *               &lt;/simpleType&gt;
     *               &lt;minLength value="1"/&gt;
     *               &lt;maxLength value="16"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "supportedCSIRSResourceListAddR16"
    })
    public static class Type1MPEType2R2PSNullR16 {

        @XmlList
        @XmlElement(name = "supportedCSI-RS-ResourceListAdd-r16", type = Integer.class)
        protected List<Integer> supportedCSIRSResourceListAddR16;

        /**
         * Gets the value of the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSupportedCSIRSResourceListAddR16().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getSupportedCSIRSResourceListAddR16() {
            if (supportedCSIRSResourceListAddR16 == null) {
                supportedCSIRSResourceListAddR16 = new ArrayList<Integer>();
            }
            return this.supportedCSIRSResourceListAddR16;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction&gt;
     *               &lt;simpleType&gt;
     *                 &lt;list&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
     *                       &lt;minInclusive value="0"/&gt;
     *                       &lt;maxInclusive value="511"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/list&gt;
     *               &lt;/simpleType&gt;
     *               &lt;minLength value="1"/&gt;
     *               &lt;maxLength value="16"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "supportedCSIRSResourceListAddR16"
    })
    public static class Type1MPType2NullR16 {

        @XmlList
        @XmlElement(name = "supportedCSI-RS-ResourceListAdd-r16", type = Integer.class)
        protected List<Integer> supportedCSIRSResourceListAddR16;

        /**
         * Gets the value of the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSupportedCSIRSResourceListAddR16().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getSupportedCSIRSResourceListAddR16() {
            if (supportedCSIRSResourceListAddR16 == null) {
                supportedCSIRSResourceListAddR16 = new ArrayList<Integer>();
            }
            return this.supportedCSIRSResourceListAddR16;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction&gt;
     *               &lt;simpleType&gt;
     *                 &lt;list&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
     *                       &lt;minInclusive value="0"/&gt;
     *                       &lt;maxInclusive value="511"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/list&gt;
     *               &lt;/simpleType&gt;
     *               &lt;minLength value="1"/&gt;
     *               &lt;maxLength value="16"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "supportedCSIRSResourceListAddR16"
    })
    public static class Type1MPType2PSNullR16 {

        @XmlList
        @XmlElement(name = "supportedCSI-RS-ResourceListAdd-r16", type = Integer.class)
        protected List<Integer> supportedCSIRSResourceListAddR16;

        /**
         * Gets the value of the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSupportedCSIRSResourceListAddR16().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getSupportedCSIRSResourceListAddR16() {
            if (supportedCSIRSResourceListAddR16 == null) {
                supportedCSIRSResourceListAddR16 = new ArrayList<Integer>();
            }
            return this.supportedCSIRSResourceListAddR16;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction&gt;
     *               &lt;simpleType&gt;
     *                 &lt;list&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
     *                       &lt;minInclusive value="0"/&gt;
     *                       &lt;maxInclusive value="511"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/list&gt;
     *               &lt;/simpleType&gt;
     *               &lt;minLength value="1"/&gt;
     *               &lt;maxLength value="16"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "supportedCSIRSResourceListAddR16"
    })
    public static class Type1MPType2Type2PSR16 {

        @XmlList
        @XmlElement(name = "supportedCSI-RS-ResourceListAdd-r16", type = Integer.class)
        protected List<Integer> supportedCSIRSResourceListAddR16;

        /**
         * Gets the value of the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSupportedCSIRSResourceListAddR16().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getSupportedCSIRSResourceListAddR16() {
            if (supportedCSIRSResourceListAddR16 == null) {
                supportedCSIRSResourceListAddR16 = new ArrayList<Integer>();
            }
            return this.supportedCSIRSResourceListAddR16;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction&gt;
     *               &lt;simpleType&gt;
     *                 &lt;list&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
     *                       &lt;minInclusive value="0"/&gt;
     *                       &lt;maxInclusive value="511"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/list&gt;
     *               &lt;/simpleType&gt;
     *               &lt;minLength value="1"/&gt;
     *               &lt;maxLength value="16"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "supportedCSIRSResourceListAddR16"
    })
    public static class Type1SPEType2R1NullR16 {

        @XmlList
        @XmlElement(name = "supportedCSI-RS-ResourceListAdd-r16", type = Integer.class)
        protected List<Integer> supportedCSIRSResourceListAddR16;

        /**
         * Gets the value of the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSupportedCSIRSResourceListAddR16().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getSupportedCSIRSResourceListAddR16() {
            if (supportedCSIRSResourceListAddR16 == null) {
                supportedCSIRSResourceListAddR16 = new ArrayList<Integer>();
            }
            return this.supportedCSIRSResourceListAddR16;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction&gt;
     *               &lt;simpleType&gt;
     *                 &lt;list&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
     *                       &lt;minInclusive value="0"/&gt;
     *                       &lt;maxInclusive value="511"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/list&gt;
     *               &lt;/simpleType&gt;
     *               &lt;minLength value="1"/&gt;
     *               &lt;maxLength value="16"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "supportedCSIRSResourceListAddR16"
    })
    public static class Type1SPEType2R1PSNullR16 {

        @XmlList
        @XmlElement(name = "supportedCSI-RS-ResourceListAdd-r16", type = Integer.class)
        protected List<Integer> supportedCSIRSResourceListAddR16;

        /**
         * Gets the value of the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSupportedCSIRSResourceListAddR16().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getSupportedCSIRSResourceListAddR16() {
            if (supportedCSIRSResourceListAddR16 == null) {
                supportedCSIRSResourceListAddR16 = new ArrayList<Integer>();
            }
            return this.supportedCSIRSResourceListAddR16;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction&gt;
     *               &lt;simpleType&gt;
     *                 &lt;list&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
     *                       &lt;minInclusive value="0"/&gt;
     *                       &lt;maxInclusive value="511"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/list&gt;
     *               &lt;/simpleType&gt;
     *               &lt;minLength value="1"/&gt;
     *               &lt;maxLength value="16"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "supportedCSIRSResourceListAddR16"
    })
    public static class Type1SPEType2R2NullR16 {

        @XmlList
        @XmlElement(name = "supportedCSI-RS-ResourceListAdd-r16", type = Integer.class)
        protected List<Integer> supportedCSIRSResourceListAddR16;

        /**
         * Gets the value of the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSupportedCSIRSResourceListAddR16().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getSupportedCSIRSResourceListAddR16() {
            if (supportedCSIRSResourceListAddR16 == null) {
                supportedCSIRSResourceListAddR16 = new ArrayList<Integer>();
            }
            return this.supportedCSIRSResourceListAddR16;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction&gt;
     *               &lt;simpleType&gt;
     *                 &lt;list&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
     *                       &lt;minInclusive value="0"/&gt;
     *                       &lt;maxInclusive value="511"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/list&gt;
     *               &lt;/simpleType&gt;
     *               &lt;minLength value="1"/&gt;
     *               &lt;maxLength value="16"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "supportedCSIRSResourceListAddR16"
    })
    public static class Type1SPEType2R2PSNullR16 {

        @XmlList
        @XmlElement(name = "supportedCSI-RS-ResourceListAdd-r16", type = Integer.class)
        protected List<Integer> supportedCSIRSResourceListAddR16;

        /**
         * Gets the value of the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSupportedCSIRSResourceListAddR16().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getSupportedCSIRSResourceListAddR16() {
            if (supportedCSIRSResourceListAddR16 == null) {
                supportedCSIRSResourceListAddR16 = new ArrayList<Integer>();
            }
            return this.supportedCSIRSResourceListAddR16;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction&gt;
     *               &lt;simpleType&gt;
     *                 &lt;list&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
     *                       &lt;minInclusive value="0"/&gt;
     *                       &lt;maxInclusive value="511"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/list&gt;
     *               &lt;/simpleType&gt;
     *               &lt;minLength value="1"/&gt;
     *               &lt;maxLength value="16"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "supportedCSIRSResourceListAddR16"
    })
    public static class Type1SPType2NullR16 {

        @XmlList
        @XmlElement(name = "supportedCSI-RS-ResourceListAdd-r16", type = Integer.class)
        protected List<Integer> supportedCSIRSResourceListAddR16;

        /**
         * Gets the value of the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSupportedCSIRSResourceListAddR16().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getSupportedCSIRSResourceListAddR16() {
            if (supportedCSIRSResourceListAddR16 == null) {
                supportedCSIRSResourceListAddR16 = new ArrayList<Integer>();
            }
            return this.supportedCSIRSResourceListAddR16;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction&gt;
     *               &lt;simpleType&gt;
     *                 &lt;list&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
     *                       &lt;minInclusive value="0"/&gt;
     *                       &lt;maxInclusive value="511"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/list&gt;
     *               &lt;/simpleType&gt;
     *               &lt;minLength value="1"/&gt;
     *               &lt;maxLength value="16"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "supportedCSIRSResourceListAddR16"
    })
    public static class Type1SPType2PSNullR16 {

        @XmlList
        @XmlElement(name = "supportedCSI-RS-ResourceListAdd-r16", type = Integer.class)
        protected List<Integer> supportedCSIRSResourceListAddR16;

        /**
         * Gets the value of the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSupportedCSIRSResourceListAddR16().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getSupportedCSIRSResourceListAddR16() {
            if (supportedCSIRSResourceListAddR16 == null) {
                supportedCSIRSResourceListAddR16 = new ArrayList<Integer>();
            }
            return this.supportedCSIRSResourceListAddR16;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction&gt;
     *               &lt;simpleType&gt;
     *                 &lt;list&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
     *                       &lt;minInclusive value="0"/&gt;
     *                       &lt;maxInclusive value="511"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/list&gt;
     *               &lt;/simpleType&gt;
     *               &lt;minLength value="1"/&gt;
     *               &lt;maxLength value="16"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "supportedCSIRSResourceListAddR16"
    })
    public static class Type1SPType2Type2PSR16 {

        @XmlList
        @XmlElement(name = "supportedCSI-RS-ResourceListAdd-r16", type = Integer.class)
        protected List<Integer> supportedCSIRSResourceListAddR16;

        /**
         * Gets the value of the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the supportedCSIRSResourceListAddR16 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSupportedCSIRSResourceListAddR16().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getSupportedCSIRSResourceListAddR16() {
            if (supportedCSIRSResourceListAddR16 == null) {
                supportedCSIRSResourceListAddR16 = new ArrayList<Integer>();
            }
            return this.supportedCSIRSResourceListAddR16;
        }

    }

}
