//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for CodebookParametersAddition-r16Mapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CodebookParametersAddition-r16Mapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="etype2-r16" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="etype2R1-r16"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction&gt;
 *                                   &lt;simpleType&gt;
 *                                     &lt;list&gt;
 *                                       &lt;simpleType&gt;
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
 *                                           &lt;minInclusive value="0"/&gt;
 *                                           &lt;maxInclusive value="511"/&gt;
 *                                         &lt;/restriction&gt;
 *                                       &lt;/simpleType&gt;
 *                                     &lt;/list&gt;
 *                                   &lt;/simpleType&gt;
 *                                   &lt;minLength value="1"/&gt;
 *                                   &lt;maxLength value="16"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="etype2R2-r16" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction&gt;
 *                                   &lt;simpleType&gt;
 *                                     &lt;list&gt;
 *                                       &lt;simpleType&gt;
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
 *                                           &lt;minInclusive value="0"/&gt;
 *                                           &lt;maxInclusive value="511"/&gt;
 *                                         &lt;/restriction&gt;
 *                                       &lt;/simpleType&gt;
 *                                     &lt;/list&gt;
 *                                   &lt;/simpleType&gt;
 *                                   &lt;minLength value="1"/&gt;
 *                                   &lt;maxLength value="16"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="paramComb7-8-r16" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *                         &lt;enumeration value="supported"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="rank3-4-r16" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *                         &lt;enumeration value="supported"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="amplitudeSubsetRestriction-r16" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *                         &lt;enumeration value="supported"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="etype2-PS-r16" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="etype2R1-PortSelection-r16"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction&gt;
 *                                   &lt;simpleType&gt;
 *                                     &lt;list&gt;
 *                                       &lt;simpleType&gt;
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
 *                                           &lt;minInclusive value="0"/&gt;
 *                                           &lt;maxInclusive value="511"/&gt;
 *                                         &lt;/restriction&gt;
 *                                       &lt;/simpleType&gt;
 *                                     &lt;/list&gt;
 *                                   &lt;/simpleType&gt;
 *                                   &lt;minLength value="1"/&gt;
 *                                   &lt;maxLength value="16"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="etype2R2-PortSelection-r16" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction&gt;
 *                                   &lt;simpleType&gt;
 *                                     &lt;list&gt;
 *                                       &lt;simpleType&gt;
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
 *                                           &lt;minInclusive value="0"/&gt;
 *                                           &lt;maxInclusive value="511"/&gt;
 *                                         &lt;/restriction&gt;
 *                                       &lt;/simpleType&gt;
 *                                     &lt;/list&gt;
 *                                   &lt;/simpleType&gt;
 *                                   &lt;minLength value="1"/&gt;
 *                                   &lt;maxLength value="16"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="rank3-4-r16" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *                         &lt;enumeration value="supported"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CodebookParametersAddition-r16Mapper", propOrder = {
    "etype2R16",
    "etype2PSR16"
})
public class CodebookParametersAdditionR16Mapper {

    @XmlElement(name = "etype2-r16")
    protected CodebookParametersAdditionR16Mapper.Etype2R16 etype2R16;
    @XmlElement(name = "etype2-PS-r16")
    protected CodebookParametersAdditionR16Mapper.Etype2PSR16 etype2PSR16;

    /**
     * Gets the value of the etype2R16 property.
     * 
     * @return
     *     possible object is
     *     {@link CodebookParametersAdditionR16Mapper.Etype2R16 }
     *     
     */
    public CodebookParametersAdditionR16Mapper.Etype2R16 getEtype2R16() {
        return etype2R16;
    }

    /**
     * Sets the value of the etype2R16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodebookParametersAdditionR16Mapper.Etype2R16 }
     *     
     */
    public void setEtype2R16(CodebookParametersAdditionR16Mapper.Etype2R16 value) {
        this.etype2R16 = value;
    }

    /**
     * Gets the value of the etype2PSR16 property.
     * 
     * @return
     *     possible object is
     *     {@link CodebookParametersAdditionR16Mapper.Etype2PSR16 }
     *     
     */
    public CodebookParametersAdditionR16Mapper.Etype2PSR16 getEtype2PSR16() {
        return etype2PSR16;
    }

    /**
     * Sets the value of the etype2PSR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodebookParametersAdditionR16Mapper.Etype2PSR16 }
     *     
     */
    public void setEtype2PSR16(CodebookParametersAdditionR16Mapper.Etype2PSR16 value) {
        this.etype2PSR16 = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="etype2R1-PortSelection-r16"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction&gt;
     *                         &lt;simpleType&gt;
     *                           &lt;list&gt;
     *                             &lt;simpleType&gt;
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
     *                                 &lt;minInclusive value="0"/&gt;
     *                                 &lt;maxInclusive value="511"/&gt;
     *                               &lt;/restriction&gt;
     *                             &lt;/simpleType&gt;
     *                           &lt;/list&gt;
     *                         &lt;/simpleType&gt;
     *                         &lt;minLength value="1"/&gt;
     *                         &lt;maxLength value="16"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="etype2R2-PortSelection-r16" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction&gt;
     *                         &lt;simpleType&gt;
     *                           &lt;list&gt;
     *                             &lt;simpleType&gt;
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
     *                                 &lt;minInclusive value="0"/&gt;
     *                                 &lt;maxInclusive value="511"/&gt;
     *                               &lt;/restriction&gt;
     *                             &lt;/simpleType&gt;
     *                           &lt;/list&gt;
     *                         &lt;/simpleType&gt;
     *                         &lt;minLength value="1"/&gt;
     *                         &lt;maxLength value="16"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="rank3-4-r16" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
     *               &lt;enumeration value="supported"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "etype2R1PortSelectionR16",
        "etype2R2PortSelectionR16",
        "rank34R16"
    })
    public static class Etype2PSR16 {

        @XmlElement(name = "etype2R1-PortSelection-r16", required = true)
        protected CodebookParametersAdditionR16Mapper.Etype2PSR16 .Etype2R1PortSelectionR16 etype2R1PortSelectionR16;
        @XmlElement(name = "etype2R2-PortSelection-r16")
        protected CodebookParametersAdditionR16Mapper.Etype2PSR16 .Etype2R2PortSelectionR16 etype2R2PortSelectionR16;
        @XmlElement(name = "rank3-4-r16")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String rank34R16;

        /**
         * Gets the value of the etype2R1PortSelectionR16 property.
         * 
         * @return
         *     possible object is
         *     {@link CodebookParametersAdditionR16Mapper.Etype2PSR16 .Etype2R1PortSelectionR16 }
         *     
         */
        public CodebookParametersAdditionR16Mapper.Etype2PSR16 .Etype2R1PortSelectionR16 getEtype2R1PortSelectionR16() {
            return etype2R1PortSelectionR16;
        }

        /**
         * Sets the value of the etype2R1PortSelectionR16 property.
         * 
         * @param value
         *     allowed object is
         *     {@link CodebookParametersAdditionR16Mapper.Etype2PSR16 .Etype2R1PortSelectionR16 }
         *     
         */
        public void setEtype2R1PortSelectionR16(CodebookParametersAdditionR16Mapper.Etype2PSR16 .Etype2R1PortSelectionR16 value) {
            this.etype2R1PortSelectionR16 = value;
        }

        /**
         * Gets the value of the etype2R2PortSelectionR16 property.
         * 
         * @return
         *     possible object is
         *     {@link CodebookParametersAdditionR16Mapper.Etype2PSR16 .Etype2R2PortSelectionR16 }
         *     
         */
        public CodebookParametersAdditionR16Mapper.Etype2PSR16 .Etype2R2PortSelectionR16 getEtype2R2PortSelectionR16() {
            return etype2R2PortSelectionR16;
        }

        /**
         * Sets the value of the etype2R2PortSelectionR16 property.
         * 
         * @param value
         *     allowed object is
         *     {@link CodebookParametersAdditionR16Mapper.Etype2PSR16 .Etype2R2PortSelectionR16 }
         *     
         */
        public void setEtype2R2PortSelectionR16(CodebookParametersAdditionR16Mapper.Etype2PSR16 .Etype2R2PortSelectionR16 value) {
            this.etype2R2PortSelectionR16 = value;
        }

        /**
         * Gets the value of the rank34R16 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRank34R16() {
            return rank34R16;
        }

        /**
         * Sets the value of the rank34R16 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRank34R16(String value) {
            this.rank34R16 = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction&gt;
         *               &lt;simpleType&gt;
         *                 &lt;list&gt;
         *                   &lt;simpleType&gt;
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
         *                       &lt;minInclusive value="0"/&gt;
         *                       &lt;maxInclusive value="511"/&gt;
         *                     &lt;/restriction&gt;
         *                   &lt;/simpleType&gt;
         *                 &lt;/list&gt;
         *               &lt;/simpleType&gt;
         *               &lt;minLength value="1"/&gt;
         *               &lt;maxLength value="16"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "supportedCSIRSResourceListAddR16"
        })
        public static class Etype2R1PortSelectionR16 {

            @XmlList
            @XmlElement(name = "supportedCSI-RS-ResourceListAdd-r16", type = Integer.class)
            protected List<Integer> supportedCSIRSResourceListAddR16;

            /**
             * Gets the value of the supportedCSIRSResourceListAddR16 property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the supportedCSIRSResourceListAddR16 property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSupportedCSIRSResourceListAddR16().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Integer }
             * 
             * 
             */
            public List<Integer> getSupportedCSIRSResourceListAddR16() {
                if (supportedCSIRSResourceListAddR16 == null) {
                    supportedCSIRSResourceListAddR16 = new ArrayList<Integer>();
                }
                return this.supportedCSIRSResourceListAddR16;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction&gt;
         *               &lt;simpleType&gt;
         *                 &lt;list&gt;
         *                   &lt;simpleType&gt;
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
         *                       &lt;minInclusive value="0"/&gt;
         *                       &lt;maxInclusive value="511"/&gt;
         *                     &lt;/restriction&gt;
         *                   &lt;/simpleType&gt;
         *                 &lt;/list&gt;
         *               &lt;/simpleType&gt;
         *               &lt;minLength value="1"/&gt;
         *               &lt;maxLength value="16"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "supportedCSIRSResourceListAddR16"
        })
        public static class Etype2R2PortSelectionR16 {

            @XmlList
            @XmlElement(name = "supportedCSI-RS-ResourceListAdd-r16", type = Integer.class)
            protected List<Integer> supportedCSIRSResourceListAddR16;

            /**
             * Gets the value of the supportedCSIRSResourceListAddR16 property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the supportedCSIRSResourceListAddR16 property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSupportedCSIRSResourceListAddR16().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Integer }
             * 
             * 
             */
            public List<Integer> getSupportedCSIRSResourceListAddR16() {
                if (supportedCSIRSResourceListAddR16 == null) {
                    supportedCSIRSResourceListAddR16 = new ArrayList<Integer>();
                }
                return this.supportedCSIRSResourceListAddR16;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="etype2R1-r16"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction&gt;
     *                         &lt;simpleType&gt;
     *                           &lt;list&gt;
     *                             &lt;simpleType&gt;
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
     *                                 &lt;minInclusive value="0"/&gt;
     *                                 &lt;maxInclusive value="511"/&gt;
     *                               &lt;/restriction&gt;
     *                             &lt;/simpleType&gt;
     *                           &lt;/list&gt;
     *                         &lt;/simpleType&gt;
     *                         &lt;minLength value="1"/&gt;
     *                         &lt;maxLength value="16"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="etype2R2-r16" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction&gt;
     *                         &lt;simpleType&gt;
     *                           &lt;list&gt;
     *                             &lt;simpleType&gt;
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
     *                                 &lt;minInclusive value="0"/&gt;
     *                                 &lt;maxInclusive value="511"/&gt;
     *                               &lt;/restriction&gt;
     *                             &lt;/simpleType&gt;
     *                           &lt;/list&gt;
     *                         &lt;/simpleType&gt;
     *                         &lt;minLength value="1"/&gt;
     *                         &lt;maxLength value="16"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="paramComb7-8-r16" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
     *               &lt;enumeration value="supported"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="rank3-4-r16" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
     *               &lt;enumeration value="supported"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="amplitudeSubsetRestriction-r16" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
     *               &lt;enumeration value="supported"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "etype2R1R16",
        "etype2R2R16",
        "paramComb78R16",
        "rank34R16",
        "amplitudeSubsetRestrictionR16"
    })
    public static class Etype2R16 {

        @XmlElement(name = "etype2R1-r16", required = true)
        protected CodebookParametersAdditionR16Mapper.Etype2R16 .Etype2R1R16 etype2R1R16;
        @XmlElement(name = "etype2R2-r16")
        protected CodebookParametersAdditionR16Mapper.Etype2R16 .Etype2R2R16 etype2R2R16;
        @XmlElement(name = "paramComb7-8-r16")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String paramComb78R16;
        @XmlElement(name = "rank3-4-r16")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String rank34R16;
        @XmlElement(name = "amplitudeSubsetRestriction-r16")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String amplitudeSubsetRestrictionR16;

        /**
         * Gets the value of the etype2R1R16 property.
         * 
         * @return
         *     possible object is
         *     {@link CodebookParametersAdditionR16Mapper.Etype2R16 .Etype2R1R16 }
         *     
         */
        public CodebookParametersAdditionR16Mapper.Etype2R16 .Etype2R1R16 getEtype2R1R16() {
            return etype2R1R16;
        }

        /**
         * Sets the value of the etype2R1R16 property.
         * 
         * @param value
         *     allowed object is
         *     {@link CodebookParametersAdditionR16Mapper.Etype2R16 .Etype2R1R16 }
         *     
         */
        public void setEtype2R1R16(CodebookParametersAdditionR16Mapper.Etype2R16 .Etype2R1R16 value) {
            this.etype2R1R16 = value;
        }

        /**
         * Gets the value of the etype2R2R16 property.
         * 
         * @return
         *     possible object is
         *     {@link CodebookParametersAdditionR16Mapper.Etype2R16 .Etype2R2R16 }
         *     
         */
        public CodebookParametersAdditionR16Mapper.Etype2R16 .Etype2R2R16 getEtype2R2R16() {
            return etype2R2R16;
        }

        /**
         * Sets the value of the etype2R2R16 property.
         * 
         * @param value
         *     allowed object is
         *     {@link CodebookParametersAdditionR16Mapper.Etype2R16 .Etype2R2R16 }
         *     
         */
        public void setEtype2R2R16(CodebookParametersAdditionR16Mapper.Etype2R16 .Etype2R2R16 value) {
            this.etype2R2R16 = value;
        }

        /**
         * Gets the value of the paramComb78R16 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getParamComb78R16() {
            return paramComb78R16;
        }

        /**
         * Sets the value of the paramComb78R16 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setParamComb78R16(String value) {
            this.paramComb78R16 = value;
        }

        /**
         * Gets the value of the rank34R16 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRank34R16() {
            return rank34R16;
        }

        /**
         * Sets the value of the rank34R16 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRank34R16(String value) {
            this.rank34R16 = value;
        }

        /**
         * Gets the value of the amplitudeSubsetRestrictionR16 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAmplitudeSubsetRestrictionR16() {
            return amplitudeSubsetRestrictionR16;
        }

        /**
         * Sets the value of the amplitudeSubsetRestrictionR16 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAmplitudeSubsetRestrictionR16(String value) {
            this.amplitudeSubsetRestrictionR16 = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction&gt;
         *               &lt;simpleType&gt;
         *                 &lt;list&gt;
         *                   &lt;simpleType&gt;
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
         *                       &lt;minInclusive value="0"/&gt;
         *                       &lt;maxInclusive value="511"/&gt;
         *                     &lt;/restriction&gt;
         *                   &lt;/simpleType&gt;
         *                 &lt;/list&gt;
         *               &lt;/simpleType&gt;
         *               &lt;minLength value="1"/&gt;
         *               &lt;maxLength value="16"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "supportedCSIRSResourceListAddR16"
        })
        public static class Etype2R1R16 {

            @XmlList
            @XmlElement(name = "supportedCSI-RS-ResourceListAdd-r16", type = Integer.class)
            protected List<Integer> supportedCSIRSResourceListAddR16;

            /**
             * Gets the value of the supportedCSIRSResourceListAddR16 property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the supportedCSIRSResourceListAddR16 property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSupportedCSIRSResourceListAddR16().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Integer }
             * 
             * 
             */
            public List<Integer> getSupportedCSIRSResourceListAddR16() {
                if (supportedCSIRSResourceListAddR16 == null) {
                    supportedCSIRSResourceListAddR16 = new ArrayList<Integer>();
                }
                return this.supportedCSIRSResourceListAddR16;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="supportedCSI-RS-ResourceListAdd-r16"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction&gt;
         *               &lt;simpleType&gt;
         *                 &lt;list&gt;
         *                   &lt;simpleType&gt;
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
         *                       &lt;minInclusive value="0"/&gt;
         *                       &lt;maxInclusive value="511"/&gt;
         *                     &lt;/restriction&gt;
         *                   &lt;/simpleType&gt;
         *                 &lt;/list&gt;
         *               &lt;/simpleType&gt;
         *               &lt;minLength value="1"/&gt;
         *               &lt;maxLength value="16"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "supportedCSIRSResourceListAddR16"
        })
        public static class Etype2R2R16 {

            @XmlList
            @XmlElement(name = "supportedCSI-RS-ResourceListAdd-r16", type = Integer.class)
            protected List<Integer> supportedCSIRSResourceListAddR16;

            /**
             * Gets the value of the supportedCSIRSResourceListAddR16 property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the supportedCSIRSResourceListAddR16 property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSupportedCSIRSResourceListAddR16().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Integer }
             * 
             * 
             */
            public List<Integer> getSupportedCSIRSResourceListAddR16() {
                if (supportedCSIRSResourceListAddR16 == null) {
                    supportedCSIRSResourceListAddR16 = new ArrayList<Integer>();
                }
                return this.supportedCSIRSResourceListAddR16;
            }

        }

    }

}
