//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for DummyDMapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DummyDMapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="maxNumberTxPortsPerResource"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="p4"/&gt;
 *               &lt;enumeration value="p8"/&gt;
 *               &lt;enumeration value="p12"/&gt;
 *               &lt;enumeration value="p16"/&gt;
 *               &lt;enumeration value="p24"/&gt;
 *               &lt;enumeration value="p32"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="maxNumberResources"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte"&gt;
 *               &lt;minInclusive value="1"/&gt;
 *               &lt;maxInclusive value="64"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="totalNumberTxPorts"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort"&gt;
 *               &lt;minInclusive value="2"/&gt;
 *               &lt;maxInclusive value="256"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="parameterLx"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte"&gt;
 *               &lt;minInclusive value="2"/&gt;
 *               &lt;maxInclusive value="4"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="amplitudeScalingType"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="wideband"/&gt;
 *               &lt;enumeration value="widebandAndSubband"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="amplitudeSubsetRestriction" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="maxNumberCSI-RS-PerResourceSet"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte"&gt;
 *               &lt;minInclusive value="1"/&gt;
 *               &lt;maxInclusive value="8"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DummyDMapper", propOrder = {
    "maxNumberTxPortsPerResource",
    "maxNumberResources",
    "totalNumberTxPorts",
    "parameterLx",
    "amplitudeScalingType",
    "amplitudeSubsetRestriction",
    "maxNumberCSIRSPerResourceSet"
})
public class DummyDMapper {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String maxNumberTxPortsPerResource;
    protected short maxNumberResources;
    protected int totalNumberTxPorts;
    protected short parameterLx;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String amplitudeScalingType;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String amplitudeSubsetRestriction;
    @XmlElement(name = "maxNumberCSI-RS-PerResourceSet")
    protected short maxNumberCSIRSPerResourceSet;

    /**
     * Gets the value of the maxNumberTxPortsPerResource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxNumberTxPortsPerResource() {
        return maxNumberTxPortsPerResource;
    }

    /**
     * Sets the value of the maxNumberTxPortsPerResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxNumberTxPortsPerResource(String value) {
        this.maxNumberTxPortsPerResource = value;
    }

    /**
     * Gets the value of the maxNumberResources property.
     * 
     */
    public short getMaxNumberResources() {
        return maxNumberResources;
    }

    /**
     * Sets the value of the maxNumberResources property.
     * 
     */
    public void setMaxNumberResources(short value) {
        this.maxNumberResources = value;
    }

    /**
     * Gets the value of the totalNumberTxPorts property.
     * 
     */
    public int getTotalNumberTxPorts() {
        return totalNumberTxPorts;
    }

    /**
     * Sets the value of the totalNumberTxPorts property.
     * 
     */
    public void setTotalNumberTxPorts(int value) {
        this.totalNumberTxPorts = value;
    }

    /**
     * Gets the value of the parameterLx property.
     * 
     */
    public short getParameterLx() {
        return parameterLx;
    }

    /**
     * Sets the value of the parameterLx property.
     * 
     */
    public void setParameterLx(short value) {
        this.parameterLx = value;
    }

    /**
     * Gets the value of the amplitudeScalingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmplitudeScalingType() {
        return amplitudeScalingType;
    }

    /**
     * Sets the value of the amplitudeScalingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmplitudeScalingType(String value) {
        this.amplitudeScalingType = value;
    }

    /**
     * Gets the value of the amplitudeSubsetRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmplitudeSubsetRestriction() {
        return amplitudeSubsetRestriction;
    }

    /**
     * Sets the value of the amplitudeSubsetRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmplitudeSubsetRestriction(String value) {
        this.amplitudeSubsetRestriction = value;
    }

    /**
     * Gets the value of the maxNumberCSIRSPerResourceSet property.
     * 
     */
    public short getMaxNumberCSIRSPerResourceSet() {
        return maxNumberCSIRSPerResourceSet;
    }

    /**
     * Sets the value of the maxNumberCSIRSPerResourceSet property.
     * 
     */
    public void setMaxNumberCSIRSPerResourceSet(short value) {
        this.maxNumberCSIRSPerResourceSet = value;
    }

}
