//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3c.dom.Element;


/**
 * <p>Java class for EUTRA-ParametersCommonMapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EUTRA-ParametersCommonMapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="mfbi-EUTRA" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="modifiedMPR-BehaviorEUTRA" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.obj-sys.com/v1.0/XMLSchema}BitString"&gt;
 *               &lt;length value="32"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="multiNS-Pmax-EUTRA" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="rs-SINR-MeasEUTRA" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ne-DC" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="nr-HO-ToEN-DC-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EUTRA-ParametersCommonMapper", propOrder = {
    "mfbiEUTRA",
    "modifiedMPRBehaviorEUTRA",
    "multiNSPmaxEUTRA",
    "rsSINRMeasEUTRA",
    "neDC",
    "nrHOToENDCR16",
    "any"
})
public class EUTRAParametersCommonMapper {

    @XmlElement(name = "mfbi-EUTRA")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String mfbiEUTRA;
    @XmlElement(name = "modifiedMPR-BehaviorEUTRA")
    protected String modifiedMPRBehaviorEUTRA;
    @XmlElement(name = "multiNS-Pmax-EUTRA")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String multiNSPmaxEUTRA;
    @XmlElement(name = "rs-SINR-MeasEUTRA")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rsSINRMeasEUTRA;
    @XmlElement(name = "ne-DC")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String neDC;
    @XmlElement(name = "nr-HO-ToEN-DC-r16")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String nrHOToENDCR16;
    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the mfbiEUTRA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMfbiEUTRA() {
        return mfbiEUTRA;
    }

    /**
     * Sets the value of the mfbiEUTRA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMfbiEUTRA(String value) {
        this.mfbiEUTRA = value;
    }

    /**
     * Gets the value of the modifiedMPRBehaviorEUTRA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiedMPRBehaviorEUTRA() {
        return modifiedMPRBehaviorEUTRA;
    }

    /**
     * Sets the value of the modifiedMPRBehaviorEUTRA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiedMPRBehaviorEUTRA(String value) {
        this.modifiedMPRBehaviorEUTRA = value;
    }

    /**
     * Gets the value of the multiNSPmaxEUTRA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultiNSPmaxEUTRA() {
        return multiNSPmaxEUTRA;
    }

    /**
     * Sets the value of the multiNSPmaxEUTRA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultiNSPmaxEUTRA(String value) {
        this.multiNSPmaxEUTRA = value;
    }

    /**
     * Gets the value of the rsSINRMeasEUTRA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRsSINRMeasEUTRA() {
        return rsSINRMeasEUTRA;
    }

    /**
     * Sets the value of the rsSINRMeasEUTRA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRsSINRMeasEUTRA(String value) {
        this.rsSINRMeasEUTRA = value;
    }

    /**
     * Gets the value of the neDC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNeDC() {
        return neDC;
    }

    /**
     * Sets the value of the neDC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNeDC(String value) {
        this.neDC = value;
    }

    /**
     * Gets the value of the nrHOToENDCR16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNrHOToENDCR16() {
        return nrHOToENDCR16;
    }

    /**
     * Sets the value of the nrHOToENDCR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNrHOToENDCR16(String value) {
        this.nrHOToENDCR16 = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
