//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for FeatureSetDownlinkPerCCMapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FeatureSetDownlinkPerCCMapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="supportedSubcarrierSpacingDL" type="{http://www.obj-sys.com/NR-RRC-Definitions}SubcarrierSpacingMapper"/&gt;
 *         &lt;element name="supportedBandwidthDL" type="{http://www.obj-sys.com/NR-RRC-Definitions}SupportedBandwidthMapper"/&gt;
 *         &lt;element name="channelBW-90mhz" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="maxNumberMIMO-LayersPDSCH" type="{http://www.obj-sys.com/NR-RRC-Definitions}MIMO-LayersDLMapper" minOccurs="0"/&gt;
 *         &lt;element name="supportedModulationOrderDL" type="{http://www.obj-sys.com/NR-RRC-Definitions}ModulationOrderMapper" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FeatureSetDownlinkPerCCMapper", propOrder = {
    "supportedSubcarrierSpacingDL",
    "supportedBandwidthDL",
    "channelBW90Mhz",
    "maxNumberMIMOLayersPDSCH",
    "supportedModulationOrderDL"
})
public class FeatureSetDownlinkPerCCMapper {

    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected SubcarrierSpacingMapper supportedSubcarrierSpacingDL;
    @XmlElement(required = true)
    protected SupportedBandwidthMapper supportedBandwidthDL;
    @XmlElement(name = "channelBW-90mhz")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String channelBW90Mhz;
    @XmlElement(name = "maxNumberMIMO-LayersPDSCH")
    @XmlSchemaType(name = "token")
    protected MIMOLayersDLMapper maxNumberMIMOLayersPDSCH;
    @XmlSchemaType(name = "token")
    protected ModulationOrderMapper supportedModulationOrderDL;

    /**
     * Gets the value of the supportedSubcarrierSpacingDL property.
     * 
     * @return
     *     possible object is
     *     {@link SubcarrierSpacingMapper }
     *     
     */
    public SubcarrierSpacingMapper getSupportedSubcarrierSpacingDL() {
        return supportedSubcarrierSpacingDL;
    }

    /**
     * Sets the value of the supportedSubcarrierSpacingDL property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubcarrierSpacingMapper }
     *     
     */
    public void setSupportedSubcarrierSpacingDL(SubcarrierSpacingMapper value) {
        this.supportedSubcarrierSpacingDL = value;
    }

    /**
     * Gets the value of the supportedBandwidthDL property.
     * 
     * @return
     *     possible object is
     *     {@link SupportedBandwidthMapper }
     *     
     */
    public SupportedBandwidthMapper getSupportedBandwidthDL() {
        return supportedBandwidthDL;
    }

    /**
     * Sets the value of the supportedBandwidthDL property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupportedBandwidthMapper }
     *     
     */
    public void setSupportedBandwidthDL(SupportedBandwidthMapper value) {
        this.supportedBandwidthDL = value;
    }

    /**
     * Gets the value of the channelBW90Mhz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannelBW90Mhz() {
        return channelBW90Mhz;
    }

    /**
     * Sets the value of the channelBW90Mhz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannelBW90Mhz(String value) {
        this.channelBW90Mhz = value;
    }

    /**
     * Gets the value of the maxNumberMIMOLayersPDSCH property.
     * 
     * @return
     *     possible object is
     *     {@link MIMOLayersDLMapper }
     *     
     */
    public MIMOLayersDLMapper getMaxNumberMIMOLayersPDSCH() {
        return maxNumberMIMOLayersPDSCH;
    }

    /**
     * Sets the value of the maxNumberMIMOLayersPDSCH property.
     * 
     * @param value
     *     allowed object is
     *     {@link MIMOLayersDLMapper }
     *     
     */
    public void setMaxNumberMIMOLayersPDSCH(MIMOLayersDLMapper value) {
        this.maxNumberMIMOLayersPDSCH = value;
    }

    /**
     * Gets the value of the supportedModulationOrderDL property.
     * 
     * @return
     *     possible object is
     *     {@link ModulationOrderMapper }
     *     
     */
    public ModulationOrderMapper getSupportedModulationOrderDL() {
        return supportedModulationOrderDL;
    }

    /**
     * Sets the value of the supportedModulationOrderDL property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModulationOrderMapper }
     *     
     */
    public void setSupportedModulationOrderDL(ModulationOrderMapper value) {
        this.supportedModulationOrderDL = value;
    }

}
