//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for InterRAT-ParametersMapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InterRAT-ParametersMapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="eutra" type="{http://www.obj-sys.com/NR-RRC-Definitions}EUTRA-ParametersMapper" minOccurs="0"/&gt;
 *         &lt;element name="utra-FDD-r16" type="{http://www.obj-sys.com/NR-RRC-Definitions}UTRA-FDD-Parameters-r16Mapper" minOccurs="0"/&gt;
 *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InterRAT-ParametersMapper", propOrder = {
    "eutra",
    "utraFDDR16",
    "any"
})
public class InterRATParametersMapper {

    protected EUTRAParametersMapper eutra;
    @XmlElement(name = "utra-FDD-r16")
    protected UTRAFDDParametersR16Mapper utraFDDR16;
    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the eutra property.
     * 
     * @return
     *     possible object is
     *     {@link EUTRAParametersMapper }
     *     
     */
    public EUTRAParametersMapper getEutra() {
        return eutra;
    }

    /**
     * Sets the value of the eutra property.
     * 
     * @param value
     *     allowed object is
     *     {@link EUTRAParametersMapper }
     *     
     */
    public void setEutra(EUTRAParametersMapper value) {
        this.eutra = value;
    }

    /**
     * Gets the value of the utraFDDR16 property.
     * 
     * @return
     *     possible object is
     *     {@link UTRAFDDParametersR16Mapper }
     *     
     */
    public UTRAFDDParametersR16Mapper getUtraFDDR16() {
        return utraFDDR16;
    }

    /**
     * Sets the value of the utraFDDR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTRAFDDParametersR16Mapper }
     *     
     */
    public void setUtraFDDR16(UTRAFDDParametersR16Mapper value) {
        this.utraFDDR16 = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
