//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MAC-Parameters-v1610Mapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MAC-Parameters-v1610Mapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="mac-ParametersFRX-Diff-r16" type="{http://www.obj-sys.com/NR-RRC-Definitions}MAC-ParametersFRX-Diff-r16Mapper" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MAC-Parameters-v1610Mapper", propOrder = {
    "macParametersFRXDiffR16"
})
public class MACParametersV1610Mapper {

    @XmlElement(name = "mac-ParametersFRX-Diff-r16")
    protected MACParametersFRXDiffR16Mapper macParametersFRXDiffR16;

    /**
     * Gets the value of the macParametersFRXDiffR16 property.
     * 
     * @return
     *     possible object is
     *     {@link MACParametersFRXDiffR16Mapper }
     *     
     */
    public MACParametersFRXDiffR16Mapper getMacParametersFRXDiffR16() {
        return macParametersFRXDiffR16;
    }

    /**
     * Sets the value of the macParametersFRXDiffR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link MACParametersFRXDiffR16Mapper }
     *     
     */
    public void setMacParametersFRXDiffR16(MACParametersFRXDiffR16Mapper value) {
        this.macParametersFRXDiffR16 = value;
    }

}
