//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MeasResultForRSSI-r16Mapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeasResultForRSSI-r16Mapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="rssi-Result-r16" type="{}RSSI-Range-r16Mapper"/&gt;
 *         &lt;element name="channelOccupancy-r16"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte"&gt;
 *               &lt;minInclusive value="0"/&gt;
 *               &lt;maxInclusive value="100"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeasResultForRSSI-r16Mapper", namespace = "", propOrder = {
    "rssiResultR16",
    "channelOccupancyR16"
})
public class MeasResultForRSSIR16Mapper {

    @XmlElement(name = "rssi-Result-r16")
    @XmlSchemaType(name = "unsignedByte")
    protected short rssiResultR16;
    @XmlElement(name = "channelOccupancy-r16")
    protected short channelOccupancyR16;

    /**
     * Gets the value of the rssiResultR16 property.
     * 
     */
    public short getRssiResultR16() {
        return rssiResultR16;
    }

    /**
     * Sets the value of the rssiResultR16 property.
     * 
     */
    public void setRssiResultR16(short value) {
        this.rssiResultR16 = value;
    }

    /**
     * Gets the value of the channelOccupancyR16 property.
     * 
     */
    public short getChannelOccupancyR16() {
        return channelOccupancyR16;
    }

    /**
     * Sets the value of the channelOccupancyR16 property.
     * 
     */
    public void setChannelOccupancyR16(short value) {
        this.channelOccupancyR16 = value;
    }

}
