//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for MeasResultEUTRAMapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeasResultEUTRAMapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="eutra-PhysCellId" type="{}PhysCellIdMapper"/&gt;
 *         &lt;element name="measResult" type="{}MeasQuantityResultsEUTRAMapper"/&gt;
 *         &lt;element name="cgi-Info" type="{}CGI-InfoEUTRAMapper" minOccurs="0"/&gt;
 *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeasResultEUTRAMapper", namespace = "", propOrder = {
    "eutraPhysCellId",
    "measResult",
    "cgiInfo",
    "any"
})
public class MeasResultEUTRAMapper {

    @XmlElement(name = "eutra-PhysCellId")
    @XmlSchemaType(name = "unsignedShort")
    protected int eutraPhysCellId;
    @XmlElement(required = true)
    protected MeasQuantityResultsEUTRAMapper measResult;
    @XmlElement(name = "cgi-Info")
    protected CGIInfoEUTRAMapper cgiInfo;
    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the eutraPhysCellId property.
     * 
     */
    public int getEutraPhysCellId() {
        return eutraPhysCellId;
    }

    /**
     * Sets the value of the eutraPhysCellId property.
     * 
     */
    public void setEutraPhysCellId(int value) {
        this.eutraPhysCellId = value;
    }

    /**
     * Gets the value of the measResult property.
     * 
     * @return
     *     possible object is
     *     {@link MeasQuantityResultsEUTRAMapper }
     *     
     */
    public MeasQuantityResultsEUTRAMapper getMeasResult() {
        return measResult;
    }

    /**
     * Sets the value of the measResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasQuantityResultsEUTRAMapper }
     *     
     */
    public void setMeasResult(MeasQuantityResultsEUTRAMapper value) {
        this.measResult = value;
    }

    /**
     * Gets the value of the cgiInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CGIInfoEUTRAMapper }
     *     
     */
    public CGIInfoEUTRAMapper getCgiInfo() {
        return cgiInfo;
    }

    /**
     * Sets the value of the cgiInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CGIInfoEUTRAMapper }
     *     
     */
    public void setCgiInfo(CGIInfoEUTRAMapper value) {
        this.cgiInfo = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
