//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for MeasResultCBR-NR-r16Mapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeasResultCBR-NR-r16Mapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sl-poolReportIdentity-r16" type="{}SL-ResourcePoolID-r16Mapper"/&gt;
 *         &lt;element name="sl-CBR-ResultsNR-r16" type="{}SL-CBR-r16Mapper"/&gt;
 *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeasResultCBR-NR-r16Mapper", namespace = "", propOrder = {
    "slPoolReportIdentityR16",
    "slCBRResultsNRR16",
    "any"
})
public class MeasResultCBRNRR16Mapper {

    @XmlElement(name = "sl-poolReportIdentity-r16")
    @XmlSchemaType(name = "unsignedByte")
    protected short slPoolReportIdentityR16;
    @XmlElement(name = "sl-CBR-ResultsNR-r16")
    @XmlSchemaType(name = "unsignedByte")
    protected short slCBRResultsNRR16;
    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the slPoolReportIdentityR16 property.
     * 
     */
    public short getSlPoolReportIdentityR16() {
        return slPoolReportIdentityR16;
    }

    /**
     * Sets the value of the slPoolReportIdentityR16 property.
     * 
     */
    public void setSlPoolReportIdentityR16(short value) {
        this.slPoolReportIdentityR16 = value;
    }

    /**
     * Gets the value of the slCBRResultsNRR16 property.
     * 
     */
    public short getSlCBRResultsNRR16() {
        return slCBRResultsNRR16;
    }

    /**
     * Sets the value of the slCBRResultsNRR16 property.
     * 
     */
    public void setSlCBRResultsNRR16(short value) {
        this.slCBRResultsNRR16 = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
