//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3c.dom.Element;


/**
 * <p>Java class for MeasAndMobParametersFRX-DiffMapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeasAndMobParametersFRX-DiffMapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ss-SINR-Meas" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="csi-RSRP-AndRSRQ-MeasWithSSB" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="csi-RSRP-AndRSRQ-MeasWithoutSSB" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="csi-SINR-Meas" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="csi-RS-RLM" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="handoverInterF" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="handoverLTE-EPC" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="handoverLTE-5GC" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="maxNumberResource-CSI-RS-RLM" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="n2"/&gt;
 *               &lt;enumeration value="n4"/&gt;
 *               &lt;enumeration value="n6"/&gt;
 *               &lt;enumeration value="n8"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="simultaneousRxDataSSB-DiffNumerology" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="nr-AutonomousGaps-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="nr-AutonomousGaps-ENDC-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="nr-AutonomousGaps-NEDC-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="nr-AutonomousGaps-NRDC-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="dummy" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="cli-RSSI-Meas-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="cli-SRS-RSRP-Meas-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="interFrequencyMeas-NoGap-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="simultaneousRxDataSSB-DiffNumerology-Inter-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="idleInactiveNR-MeasReport-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="idleInactiveNR-MeasBeamReport-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="increasedNumberofCSIRSPerMO-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeasAndMobParametersFRX-DiffMapper", propOrder = {
    "ssSINRMeas",
    "csiRSRPAndRSRQMeasWithSSB",
    "csiRSRPAndRSRQMeasWithoutSSB",
    "csiSINRMeas",
    "csiRSRLM",
    "handoverInterF",
    "handoverLTEEPC",
    "handoverLTE5GC",
    "maxNumberResourceCSIRSRLM",
    "simultaneousRxDataSSBDiffNumerology",
    "nrAutonomousGapsR16",
    "nrAutonomousGapsENDCR16",
    "nrAutonomousGapsNEDCR16",
    "nrAutonomousGapsNRDCR16",
    "dummy",
    "cliRSSIMeasR16",
    "cliSRSRSRPMeasR16",
    "interFrequencyMeasNoGapR16",
    "simultaneousRxDataSSBDiffNumerologyInterR16",
    "idleInactiveNRMeasReportR16",
    "idleInactiveNRMeasBeamReportR16",
    "increasedNumberofCSIRSPerMOR16",
    "any"
})
public class MeasAndMobParametersFRXDiffMapper {

    @XmlElement(name = "ss-SINR-Meas")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ssSINRMeas;
    @XmlElement(name = "csi-RSRP-AndRSRQ-MeasWithSSB")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String csiRSRPAndRSRQMeasWithSSB;
    @XmlElement(name = "csi-RSRP-AndRSRQ-MeasWithoutSSB")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String csiRSRPAndRSRQMeasWithoutSSB;
    @XmlElement(name = "csi-SINR-Meas")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String csiSINRMeas;
    @XmlElement(name = "csi-RS-RLM")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String csiRSRLM;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String handoverInterF;
    @XmlElement(name = "handoverLTE-EPC")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String handoverLTEEPC;
    @XmlElement(name = "handoverLTE-5GC")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String handoverLTE5GC;
    @XmlElement(name = "maxNumberResource-CSI-RS-RLM")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String maxNumberResourceCSIRSRLM;
    @XmlElement(name = "simultaneousRxDataSSB-DiffNumerology")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String simultaneousRxDataSSBDiffNumerology;
    @XmlElement(name = "nr-AutonomousGaps-r16")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String nrAutonomousGapsR16;
    @XmlElement(name = "nr-AutonomousGaps-ENDC-r16")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String nrAutonomousGapsENDCR16;
    @XmlElement(name = "nr-AutonomousGaps-NEDC-r16")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String nrAutonomousGapsNEDCR16;
    @XmlElement(name = "nr-AutonomousGaps-NRDC-r16")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String nrAutonomousGapsNRDCR16;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dummy;
    @XmlElement(name = "cli-RSSI-Meas-r16")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cliRSSIMeasR16;
    @XmlElement(name = "cli-SRS-RSRP-Meas-r16")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cliSRSRSRPMeasR16;
    @XmlElement(name = "interFrequencyMeas-NoGap-r16")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String interFrequencyMeasNoGapR16;
    @XmlElement(name = "simultaneousRxDataSSB-DiffNumerology-Inter-r16")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String simultaneousRxDataSSBDiffNumerologyInterR16;
    @XmlElement(name = "idleInactiveNR-MeasReport-r16")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String idleInactiveNRMeasReportR16;
    @XmlElement(name = "idleInactiveNR-MeasBeamReport-r16")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String idleInactiveNRMeasBeamReportR16;
    @XmlElement(name = "increasedNumberofCSIRSPerMO-r16")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String increasedNumberofCSIRSPerMOR16;
    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the ssSINRMeas property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsSINRMeas() {
        return ssSINRMeas;
    }

    /**
     * Sets the value of the ssSINRMeas property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsSINRMeas(String value) {
        this.ssSINRMeas = value;
    }

    /**
     * Gets the value of the csiRSRPAndRSRQMeasWithSSB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCsiRSRPAndRSRQMeasWithSSB() {
        return csiRSRPAndRSRQMeasWithSSB;
    }

    /**
     * Sets the value of the csiRSRPAndRSRQMeasWithSSB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCsiRSRPAndRSRQMeasWithSSB(String value) {
        this.csiRSRPAndRSRQMeasWithSSB = value;
    }

    /**
     * Gets the value of the csiRSRPAndRSRQMeasWithoutSSB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCsiRSRPAndRSRQMeasWithoutSSB() {
        return csiRSRPAndRSRQMeasWithoutSSB;
    }

    /**
     * Sets the value of the csiRSRPAndRSRQMeasWithoutSSB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCsiRSRPAndRSRQMeasWithoutSSB(String value) {
        this.csiRSRPAndRSRQMeasWithoutSSB = value;
    }

    /**
     * Gets the value of the csiSINRMeas property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCsiSINRMeas() {
        return csiSINRMeas;
    }

    /**
     * Sets the value of the csiSINRMeas property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCsiSINRMeas(String value) {
        this.csiSINRMeas = value;
    }

    /**
     * Gets the value of the csiRSRLM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCsiRSRLM() {
        return csiRSRLM;
    }

    /**
     * Sets the value of the csiRSRLM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCsiRSRLM(String value) {
        this.csiRSRLM = value;
    }

    /**
     * Gets the value of the handoverInterF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandoverInterF() {
        return handoverInterF;
    }

    /**
     * Sets the value of the handoverInterF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandoverInterF(String value) {
        this.handoverInterF = value;
    }

    /**
     * Gets the value of the handoverLTEEPC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandoverLTEEPC() {
        return handoverLTEEPC;
    }

    /**
     * Sets the value of the handoverLTEEPC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandoverLTEEPC(String value) {
        this.handoverLTEEPC = value;
    }

    /**
     * Gets the value of the handoverLTE5GC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandoverLTE5GC() {
        return handoverLTE5GC;
    }

    /**
     * Sets the value of the handoverLTE5GC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandoverLTE5GC(String value) {
        this.handoverLTE5GC = value;
    }

    /**
     * Gets the value of the maxNumberResourceCSIRSRLM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxNumberResourceCSIRSRLM() {
        return maxNumberResourceCSIRSRLM;
    }

    /**
     * Sets the value of the maxNumberResourceCSIRSRLM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxNumberResourceCSIRSRLM(String value) {
        this.maxNumberResourceCSIRSRLM = value;
    }

    /**
     * Gets the value of the simultaneousRxDataSSBDiffNumerology property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimultaneousRxDataSSBDiffNumerology() {
        return simultaneousRxDataSSBDiffNumerology;
    }

    /**
     * Sets the value of the simultaneousRxDataSSBDiffNumerology property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimultaneousRxDataSSBDiffNumerology(String value) {
        this.simultaneousRxDataSSBDiffNumerology = value;
    }

    /**
     * Gets the value of the nrAutonomousGapsR16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNrAutonomousGapsR16() {
        return nrAutonomousGapsR16;
    }

    /**
     * Sets the value of the nrAutonomousGapsR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNrAutonomousGapsR16(String value) {
        this.nrAutonomousGapsR16 = value;
    }

    /**
     * Gets the value of the nrAutonomousGapsENDCR16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNrAutonomousGapsENDCR16() {
        return nrAutonomousGapsENDCR16;
    }

    /**
     * Sets the value of the nrAutonomousGapsENDCR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNrAutonomousGapsENDCR16(String value) {
        this.nrAutonomousGapsENDCR16 = value;
    }

    /**
     * Gets the value of the nrAutonomousGapsNEDCR16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNrAutonomousGapsNEDCR16() {
        return nrAutonomousGapsNEDCR16;
    }

    /**
     * Sets the value of the nrAutonomousGapsNEDCR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNrAutonomousGapsNEDCR16(String value) {
        this.nrAutonomousGapsNEDCR16 = value;
    }

    /**
     * Gets the value of the nrAutonomousGapsNRDCR16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNrAutonomousGapsNRDCR16() {
        return nrAutonomousGapsNRDCR16;
    }

    /**
     * Sets the value of the nrAutonomousGapsNRDCR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNrAutonomousGapsNRDCR16(String value) {
        this.nrAutonomousGapsNRDCR16 = value;
    }

    /**
     * Gets the value of the dummy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDummy() {
        return dummy;
    }

    /**
     * Sets the value of the dummy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDummy(String value) {
        this.dummy = value;
    }

    /**
     * Gets the value of the cliRSSIMeasR16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCliRSSIMeasR16() {
        return cliRSSIMeasR16;
    }

    /**
     * Sets the value of the cliRSSIMeasR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCliRSSIMeasR16(String value) {
        this.cliRSSIMeasR16 = value;
    }

    /**
     * Gets the value of the cliSRSRSRPMeasR16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCliSRSRSRPMeasR16() {
        return cliSRSRSRPMeasR16;
    }

    /**
     * Sets the value of the cliSRSRSRPMeasR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCliSRSRSRPMeasR16(String value) {
        this.cliSRSRSRPMeasR16 = value;
    }

    /**
     * Gets the value of the interFrequencyMeasNoGapR16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterFrequencyMeasNoGapR16() {
        return interFrequencyMeasNoGapR16;
    }

    /**
     * Sets the value of the interFrequencyMeasNoGapR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterFrequencyMeasNoGapR16(String value) {
        this.interFrequencyMeasNoGapR16 = value;
    }

    /**
     * Gets the value of the simultaneousRxDataSSBDiffNumerologyInterR16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimultaneousRxDataSSBDiffNumerologyInterR16() {
        return simultaneousRxDataSSBDiffNumerologyInterR16;
    }

    /**
     * Sets the value of the simultaneousRxDataSSBDiffNumerologyInterR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimultaneousRxDataSSBDiffNumerologyInterR16(String value) {
        this.simultaneousRxDataSSBDiffNumerologyInterR16 = value;
    }

    /**
     * Gets the value of the idleInactiveNRMeasReportR16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdleInactiveNRMeasReportR16() {
        return idleInactiveNRMeasReportR16;
    }

    /**
     * Sets the value of the idleInactiveNRMeasReportR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdleInactiveNRMeasReportR16(String value) {
        this.idleInactiveNRMeasReportR16 = value;
    }

    /**
     * Gets the value of the idleInactiveNRMeasBeamReportR16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdleInactiveNRMeasBeamReportR16() {
        return idleInactiveNRMeasBeamReportR16;
    }

    /**
     * Sets the value of the idleInactiveNRMeasBeamReportR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdleInactiveNRMeasBeamReportR16(String value) {
        this.idleInactiveNRMeasBeamReportR16 = value;
    }

    /**
     * Gets the value of the increasedNumberofCSIRSPerMOR16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncreasedNumberofCSIRSPerMOR16() {
        return increasedNumberofCSIRSPerMOR16;
    }

    /**
     * Sets the value of the increasedNumberofCSIRSPerMOR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncreasedNumberofCSIRSPerMOR16(String value) {
        this.increasedNumberofCSIRSPerMOR16 = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
