//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for MRDC-Parameters-v1630Mapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MRDC-Parameters-v1630Mapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="maxUplinkDutyCycle-interBandENDC-FDD-TDD-PC2-r16" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="maxUplinkDutyCycle-FDD-TDD-EN-DC1-r16" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *                         &lt;enumeration value="n30"/&gt;
 *                         &lt;enumeration value="n40"/&gt;
 *                         &lt;enumeration value="n50"/&gt;
 *                         &lt;enumeration value="n60"/&gt;
 *                         &lt;enumeration value="n70"/&gt;
 *                         &lt;enumeration value="n80"/&gt;
 *                         &lt;enumeration value="n90"/&gt;
 *                         &lt;enumeration value="n100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="maxUplinkDutyCycle-FDD-TDD-EN-DC2-r16" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *                         &lt;enumeration value="n30"/&gt;
 *                         &lt;enumeration value="n40"/&gt;
 *                         &lt;enumeration value="n50"/&gt;
 *                         &lt;enumeration value="n60"/&gt;
 *                         &lt;enumeration value="n70"/&gt;
 *                         &lt;enumeration value="n80"/&gt;
 *                         &lt;enumeration value="n90"/&gt;
 *                         &lt;enumeration value="n100"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="interBandMRDC-WithOverlapDL-Bands-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MRDC-Parameters-v1630Mapper", propOrder = {
    "maxUplinkDutyCycleInterBandENDCFDDTDDPC2R16",
    "interBandMRDCWithOverlapDLBandsR16"
})
public class MRDCParametersV1630Mapper {

    @XmlElement(name = "maxUplinkDutyCycle-interBandENDC-FDD-TDD-PC2-r16")
    protected MRDCParametersV1630Mapper.MaxUplinkDutyCycleInterBandENDCFDDTDDPC2R16 maxUplinkDutyCycleInterBandENDCFDDTDDPC2R16;
    @XmlElement(name = "interBandMRDC-WithOverlapDL-Bands-r16")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String interBandMRDCWithOverlapDLBandsR16;

    /**
     * Gets the value of the maxUplinkDutyCycleInterBandENDCFDDTDDPC2R16 property.
     * 
     * @return
     *     possible object is
     *     {@link MRDCParametersV1630Mapper.MaxUplinkDutyCycleInterBandENDCFDDTDDPC2R16 }
     *     
     */
    public MRDCParametersV1630Mapper.MaxUplinkDutyCycleInterBandENDCFDDTDDPC2R16 getMaxUplinkDutyCycleInterBandENDCFDDTDDPC2R16() {
        return maxUplinkDutyCycleInterBandENDCFDDTDDPC2R16;
    }

    /**
     * Sets the value of the maxUplinkDutyCycleInterBandENDCFDDTDDPC2R16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link MRDCParametersV1630Mapper.MaxUplinkDutyCycleInterBandENDCFDDTDDPC2R16 }
     *     
     */
    public void setMaxUplinkDutyCycleInterBandENDCFDDTDDPC2R16(MRDCParametersV1630Mapper.MaxUplinkDutyCycleInterBandENDCFDDTDDPC2R16 value) {
        this.maxUplinkDutyCycleInterBandENDCFDDTDDPC2R16 = value;
    }

    /**
     * Gets the value of the interBandMRDCWithOverlapDLBandsR16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterBandMRDCWithOverlapDLBandsR16() {
        return interBandMRDCWithOverlapDLBandsR16;
    }

    /**
     * Sets the value of the interBandMRDCWithOverlapDLBandsR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterBandMRDCWithOverlapDLBandsR16(String value) {
        this.interBandMRDCWithOverlapDLBandsR16 = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="maxUplinkDutyCycle-FDD-TDD-EN-DC1-r16" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
     *               &lt;enumeration value="n30"/&gt;
     *               &lt;enumeration value="n40"/&gt;
     *               &lt;enumeration value="n50"/&gt;
     *               &lt;enumeration value="n60"/&gt;
     *               &lt;enumeration value="n70"/&gt;
     *               &lt;enumeration value="n80"/&gt;
     *               &lt;enumeration value="n90"/&gt;
     *               &lt;enumeration value="n100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="maxUplinkDutyCycle-FDD-TDD-EN-DC2-r16" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
     *               &lt;enumeration value="n30"/&gt;
     *               &lt;enumeration value="n40"/&gt;
     *               &lt;enumeration value="n50"/&gt;
     *               &lt;enumeration value="n60"/&gt;
     *               &lt;enumeration value="n70"/&gt;
     *               &lt;enumeration value="n80"/&gt;
     *               &lt;enumeration value="n90"/&gt;
     *               &lt;enumeration value="n100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "maxUplinkDutyCycleFDDTDDENDC1R16",
        "maxUplinkDutyCycleFDDTDDENDC2R16"
    })
    public static class MaxUplinkDutyCycleInterBandENDCFDDTDDPC2R16 {

        @XmlElement(name = "maxUplinkDutyCycle-FDD-TDD-EN-DC1-r16")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String maxUplinkDutyCycleFDDTDDENDC1R16;
        @XmlElement(name = "maxUplinkDutyCycle-FDD-TDD-EN-DC2-r16")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String maxUplinkDutyCycleFDDTDDENDC2R16;

        /**
         * Gets the value of the maxUplinkDutyCycleFDDTDDENDC1R16 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaxUplinkDutyCycleFDDTDDENDC1R16() {
            return maxUplinkDutyCycleFDDTDDENDC1R16;
        }

        /**
         * Sets the value of the maxUplinkDutyCycleFDDTDDENDC1R16 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaxUplinkDutyCycleFDDTDDENDC1R16(String value) {
            this.maxUplinkDutyCycleFDDTDDENDC1R16 = value;
        }

        /**
         * Gets the value of the maxUplinkDutyCycleFDDTDDENDC2R16 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaxUplinkDutyCycleFDDTDDENDC2R16() {
            return maxUplinkDutyCycleFDDTDDENDC2R16;
        }

        /**
         * Sets the value of the maxUplinkDutyCycleFDDTDDENDC2R16 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaxUplinkDutyCycleFDDTDDENDC2R16(String value) {
            this.maxUplinkDutyCycleFDDTDDENDC2R16 = value;
        }

    }

}
