//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for PDCCH-MonitoringOccasions-r16Mapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PDCCH-MonitoringOccasions-r16Mapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="period7span3-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="period4span3-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="period2span2-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PDCCH-MonitoringOccasions-r16Mapper", propOrder = {
    "period7Span3R16",
    "period4Span3R16",
    "period2Span2R16"
})
public class PDCCHMonitoringOccasionsR16Mapper {

    @XmlElement(name = "period7span3-r16")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String period7Span3R16;
    @XmlElement(name = "period4span3-r16")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String period4Span3R16;
    @XmlElement(name = "period2span2-r16")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String period2Span2R16;

    /**
     * Gets the value of the period7Span3R16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriod7Span3R16() {
        return period7Span3R16;
    }

    /**
     * Sets the value of the period7Span3R16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriod7Span3R16(String value) {
        this.period7Span3R16 = value;
    }

    /**
     * Gets the value of the period4Span3R16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriod4Span3R16() {
        return period4Span3R16;
    }

    /**
     * Sets the value of the period4Span3R16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriod4Span3R16(String value) {
        this.period4Span3R16 = value;
    }

    /**
     * Gets the value of the period2Span2R16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriod2Span2R16() {
        return period2Span2R16;
    }

    /**
     * Sets the value of the period2Span2R16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriod2Span2R16(String value) {
        this.period2Span2R16 = value;
    }

}
