//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for PowSav-Parameters-r16Mapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PowSav-Parameters-r16Mapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="powSav-ParametersCommon-r16" type="{http://www.obj-sys.com/NR-RRC-Definitions}PowSav-ParametersCommon-r16Mapper" minOccurs="0"/&gt;
 *         &lt;element name="powSav-ParametersFRX-Diff-r16" type="{http://www.obj-sys.com/NR-RRC-Definitions}PowSav-ParametersFRX-Diff-r16Mapper" minOccurs="0"/&gt;
 *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PowSav-Parameters-r16Mapper", propOrder = {
    "powSavParametersCommonR16",
    "powSavParametersFRXDiffR16",
    "any"
})
public class PowSavParametersR16Mapper {

    @XmlElement(name = "powSav-ParametersCommon-r16")
    protected PowSavParametersCommonR16Mapper powSavParametersCommonR16;
    @XmlElement(name = "powSav-ParametersFRX-Diff-r16")
    protected PowSavParametersFRXDiffR16Mapper powSavParametersFRXDiffR16;
    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the powSavParametersCommonR16 property.
     * 
     * @return
     *     possible object is
     *     {@link PowSavParametersCommonR16Mapper }
     *     
     */
    public PowSavParametersCommonR16Mapper getPowSavParametersCommonR16() {
        return powSavParametersCommonR16;
    }

    /**
     * Sets the value of the powSavParametersCommonR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PowSavParametersCommonR16Mapper }
     *     
     */
    public void setPowSavParametersCommonR16(PowSavParametersCommonR16Mapper value) {
        this.powSavParametersCommonR16 = value;
    }

    /**
     * Gets the value of the powSavParametersFRXDiffR16 property.
     * 
     * @return
     *     possible object is
     *     {@link PowSavParametersFRXDiffR16Mapper }
     *     
     */
    public PowSavParametersFRXDiffR16Mapper getPowSavParametersFRXDiffR16() {
        return powSavParametersFRXDiffR16;
    }

    /**
     * Sets the value of the powSavParametersFRXDiffR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PowSavParametersFRXDiffR16Mapper }
     *     
     */
    public void setPowSavParametersFRXDiffR16(PowSavParametersFRXDiffR16Mapper value) {
        this.powSavParametersFRXDiffR16 = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
