//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for PUCCH-Grp-CarrierTypes-r16Mapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PUCCH-Grp-CarrierTypes-r16Mapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="fr1-NonSharedTDD-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="fr1-SharedTDD-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="fr1-NonSharedFDD-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="fr2-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PUCCH-Grp-CarrierTypes-r16Mapper", propOrder = {
    "fr1NonSharedTDDR16",
    "fr1SharedTDDR16",
    "fr1NonSharedFDDR16",
    "fr2R16"
})
public class PUCCHGrpCarrierTypesR16Mapper {

    @XmlElement(name = "fr1-NonSharedTDD-r16")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String fr1NonSharedTDDR16;
    @XmlElement(name = "fr1-SharedTDD-r16")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String fr1SharedTDDR16;
    @XmlElement(name = "fr1-NonSharedFDD-r16")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String fr1NonSharedFDDR16;
    @XmlElement(name = "fr2-r16")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String fr2R16;

    /**
     * Gets the value of the fr1NonSharedTDDR16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFr1NonSharedTDDR16() {
        return fr1NonSharedTDDR16;
    }

    /**
     * Sets the value of the fr1NonSharedTDDR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFr1NonSharedTDDR16(String value) {
        this.fr1NonSharedTDDR16 = value;
    }

    /**
     * Gets the value of the fr1SharedTDDR16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFr1SharedTDDR16() {
        return fr1SharedTDDR16;
    }

    /**
     * Sets the value of the fr1SharedTDDR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFr1SharedTDDR16(String value) {
        this.fr1SharedTDDR16 = value;
    }

    /**
     * Gets the value of the fr1NonSharedFDDR16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFr1NonSharedFDDR16() {
        return fr1NonSharedFDDR16;
    }

    /**
     * Sets the value of the fr1NonSharedFDDR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFr1NonSharedFDDR16(String value) {
        this.fr1NonSharedFDDR16 = value;
    }

    /**
     * Gets the value of the fr2R16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFr2R16() {
        return fr2R16;
    }

    /**
     * Sets the value of the fr2R16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFr2R16(String value) {
        this.fr2R16 = value;
    }

}
