//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResultsPerCSI-RS-IndexListMapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResultsPerCSI-RS-IndexListMapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="64"&gt;
 *         &lt;element name="ResultsPerCSI-RS-Index" type="{}ResultsPerCSI-RS-IndexMapper"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResultsPerCSI-RS-IndexListMapper", namespace = "", propOrder = {
    "resultsPerCSIRSIndex"
})
public class ResultsPerCSIRSIndexListMapper {

    @XmlElement(name = "ResultsPerCSI-RS-Index", required = true)
    protected List<ResultsPerCSIRSIndexMapper> resultsPerCSIRSIndex;

    /**
     * Gets the value of the resultsPerCSIRSIndex property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resultsPerCSIRSIndex property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResultsPerCSIRSIndex().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResultsPerCSIRSIndexMapper }
     * 
     * 
     */
    public List<ResultsPerCSIRSIndexMapper> getResultsPerCSIRSIndex() {
        if (resultsPerCSIRSIndex == null) {
            resultsPerCSIRSIndex = new ArrayList<ResultsPerCSIRSIndexMapper>();
        }
        return this.resultsPerCSIRSIndex;
    }

}
