//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3c.dom.Element;


/**
 * <p>Java class for RLC-ParametersMapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RLC-ParametersMapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="am-WithShortSN" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="um-WithShortSN" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="um-WithLongSN" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="extendedT-PollRetransmit-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="extendedT-StatusProhibit-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RLC-ParametersMapper", propOrder = {
    "amWithShortSN",
    "umWithShortSN",
    "umWithLongSN",
    "extendedTPollRetransmitR16",
    "extendedTStatusProhibitR16",
    "any"
})
public class RLCParametersMapper {

    @XmlElement(name = "am-WithShortSN")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String amWithShortSN;
    @XmlElement(name = "um-WithShortSN")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String umWithShortSN;
    @XmlElement(name = "um-WithLongSN")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String umWithLongSN;
    @XmlElement(name = "extendedT-PollRetransmit-r16")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String extendedTPollRetransmitR16;
    @XmlElement(name = "extendedT-StatusProhibit-r16")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String extendedTStatusProhibitR16;
    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the amWithShortSN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmWithShortSN() {
        return amWithShortSN;
    }

    /**
     * Sets the value of the amWithShortSN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmWithShortSN(String value) {
        this.amWithShortSN = value;
    }

    /**
     * Gets the value of the umWithShortSN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUmWithShortSN() {
        return umWithShortSN;
    }

    /**
     * Sets the value of the umWithShortSN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUmWithShortSN(String value) {
        this.umWithShortSN = value;
    }

    /**
     * Gets the value of the umWithLongSN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUmWithLongSN() {
        return umWithLongSN;
    }

    /**
     * Sets the value of the umWithLongSN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUmWithLongSN(String value) {
        this.umWithLongSN = value;
    }

    /**
     * Gets the value of the extendedTPollRetransmitR16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtendedTPollRetransmitR16() {
        return extendedTPollRetransmitR16;
    }

    /**
     * Sets the value of the extendedTPollRetransmitR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtendedTPollRetransmitR16(String value) {
        this.extendedTPollRetransmitR16 = value;
    }

    /**
     * Gets the value of the extendedTStatusProhibitR16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtendedTStatusProhibitR16() {
        return extendedTStatusProhibitR16;
    }

    /**
     * Sets the value of the extendedTStatusProhibitR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtendedTStatusProhibitR16(String value) {
        this.extendedTStatusProhibitR16 = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
