//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for SRS-PosResourceAP-r16Mapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SRS-PosResourceAP-r16Mapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="maxNumberAP-SRS-PosResourcesPerBWP-r16"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="n1"/&gt;
 *               &lt;enumeration value="n2"/&gt;
 *               &lt;enumeration value="n4"/&gt;
 *               &lt;enumeration value="n8"/&gt;
 *               &lt;enumeration value="n16"/&gt;
 *               &lt;enumeration value="n32"/&gt;
 *               &lt;enumeration value="n64"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="maxNumberAP-SRS-PosResourcesPerBWP-PerSlot-r16"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="n1"/&gt;
 *               &lt;enumeration value="n2"/&gt;
 *               &lt;enumeration value="n3"/&gt;
 *               &lt;enumeration value="n4"/&gt;
 *               &lt;enumeration value="n5"/&gt;
 *               &lt;enumeration value="n6"/&gt;
 *               &lt;enumeration value="n8"/&gt;
 *               &lt;enumeration value="n10"/&gt;
 *               &lt;enumeration value="n12"/&gt;
 *               &lt;enumeration value="n14"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SRS-PosResourceAP-r16Mapper", propOrder = {
    "maxNumberAPSRSPosResourcesPerBWPR16",
    "maxNumberAPSRSPosResourcesPerBWPPerSlotR16"
})
public class SRSPosResourceAPR16Mapper {

    @XmlElement(name = "maxNumberAP-SRS-PosResourcesPerBWP-r16", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String maxNumberAPSRSPosResourcesPerBWPR16;
    @XmlElement(name = "maxNumberAP-SRS-PosResourcesPerBWP-PerSlot-r16", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String maxNumberAPSRSPosResourcesPerBWPPerSlotR16;

    /**
     * Gets the value of the maxNumberAPSRSPosResourcesPerBWPR16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxNumberAPSRSPosResourcesPerBWPR16() {
        return maxNumberAPSRSPosResourcesPerBWPR16;
    }

    /**
     * Sets the value of the maxNumberAPSRSPosResourcesPerBWPR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxNumberAPSRSPosResourcesPerBWPR16(String value) {
        this.maxNumberAPSRSPosResourcesPerBWPR16 = value;
    }

    /**
     * Gets the value of the maxNumberAPSRSPosResourcesPerBWPPerSlotR16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxNumberAPSRSPosResourcesPerBWPPerSlotR16() {
        return maxNumberAPSRSPosResourcesPerBWPPerSlotR16;
    }

    /**
     * Sets the value of the maxNumberAPSRSPosResourcesPerBWPPerSlotR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxNumberAPSRSPosResourcesPerBWPPerSlotR16(String value) {
        this.maxNumberAPSRSPosResourcesPerBWPPerSlotR16 = value;
    }

}
