//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for UE-NR-Capability-v1640Mapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UE-NR-Capability-v1640Mapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="redirectAtResumeByNAS-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;enumeration value="supported"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="phy-ParametersSharedSpectrumChAccess-r16" type="{http://www.obj-sys.com/NR-RRC-Definitions}Phy-ParametersSharedSpectrumChAccess-r16Mapper" minOccurs="0"/&gt;
 *         &lt;element name="nonCriticalExtension" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UE-NR-Capability-v1640Mapper", propOrder = {
    "redirectAtResumeByNASR16",
    "phyParametersSharedSpectrumChAccessR16",
    "nonCriticalExtension"
})
public class UENRCapabilityV1640Mapper {

    @XmlElement(name = "redirectAtResumeByNAS-r16")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String redirectAtResumeByNASR16;
    @XmlElement(name = "phy-ParametersSharedSpectrumChAccess-r16")
    protected PhyParametersSharedSpectrumChAccessR16Mapper phyParametersSharedSpectrumChAccessR16;
    protected UENRCapabilityV1640Mapper.NonCriticalExtension nonCriticalExtension;

    /**
     * Gets the value of the redirectAtResumeByNASR16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRedirectAtResumeByNASR16() {
        return redirectAtResumeByNASR16;
    }

    /**
     * Sets the value of the redirectAtResumeByNASR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRedirectAtResumeByNASR16(String value) {
        this.redirectAtResumeByNASR16 = value;
    }

    /**
     * Gets the value of the phyParametersSharedSpectrumChAccessR16 property.
     * 
     * @return
     *     possible object is
     *     {@link PhyParametersSharedSpectrumChAccessR16Mapper }
     *     
     */
    public PhyParametersSharedSpectrumChAccessR16Mapper getPhyParametersSharedSpectrumChAccessR16() {
        return phyParametersSharedSpectrumChAccessR16;
    }

    /**
     * Sets the value of the phyParametersSharedSpectrumChAccessR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhyParametersSharedSpectrumChAccessR16Mapper }
     *     
     */
    public void setPhyParametersSharedSpectrumChAccessR16(PhyParametersSharedSpectrumChAccessR16Mapper value) {
        this.phyParametersSharedSpectrumChAccessR16 = value;
    }

    /**
     * Gets the value of the nonCriticalExtension property.
     * 
     * @return
     *     possible object is
     *     {@link UENRCapabilityV1640Mapper.NonCriticalExtension }
     *     
     */
    public UENRCapabilityV1640Mapper.NonCriticalExtension getNonCriticalExtension() {
        return nonCriticalExtension;
    }

    /**
     * Sets the value of the nonCriticalExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link UENRCapabilityV1640Mapper.NonCriticalExtension }
     *     
     */
    public void setNonCriticalExtension(UENRCapabilityV1640Mapper.NonCriticalExtension value) {
        this.nonCriticalExtension = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class NonCriticalExtension {


    }

}
