//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for UE-NR-Capability-v1560Mapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UE-NR-Capability-v1560Mapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="nrdc-Parameters" type="{http://www.obj-sys.com/NR-RRC-Definitions}NRDC-ParametersMapper" minOccurs="0"/&gt;
 *         &lt;element name="receivedFilters" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/&gt;
 *         &lt;element name="nonCriticalExtension" type="{http://www.obj-sys.com/NR-RRC-Definitions}UE-NR-Capability-v1570Mapper" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UE-NR-Capability-v1560Mapper", propOrder = {
    "nrdcParameters",
    "receivedFilters",
    "nonCriticalExtension"
})
public class UENRCapabilityV1560Mapper {

    @XmlElement(name = "nrdc-Parameters")
    protected NRDCParametersMapper nrdcParameters;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] receivedFilters;
    protected UENRCapabilityV1570Mapper nonCriticalExtension;

    /**
     * Gets the value of the nrdcParameters property.
     * 
     * @return
     *     possible object is
     *     {@link NRDCParametersMapper }
     *     
     */
    public NRDCParametersMapper getNrdcParameters() {
        return nrdcParameters;
    }

    /**
     * Sets the value of the nrdcParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link NRDCParametersMapper }
     *     
     */
    public void setNrdcParameters(NRDCParametersMapper value) {
        this.nrdcParameters = value;
    }

    /**
     * Gets the value of the receivedFilters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getReceivedFilters() {
        return receivedFilters;
    }

    /**
     * Sets the value of the receivedFilters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceivedFilters(byte[] value) {
        this.receivedFilters = value;
    }

    /**
     * Gets the value of the nonCriticalExtension property.
     * 
     * @return
     *     possible object is
     *     {@link UENRCapabilityV1570Mapper }
     *     
     */
    public UENRCapabilityV1570Mapper getNonCriticalExtension() {
        return nonCriticalExtension;
    }

    /**
     * Sets the value of the nonCriticalExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link UENRCapabilityV1570Mapper }
     *     
     */
    public void setNonCriticalExtension(UENRCapabilityV1570Mapper value) {
        this.nonCriticalExtension = value;
    }

}
