//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.08 at 04:50:40 PM IST 
//


package com.ericsson.tool.asn.nr.mapper.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for WLAN-RTT-r16Mapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WLAN-RTT-r16Mapper"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="rttValue-r16"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt"&gt;
 *               &lt;minInclusive value="0"/&gt;
 *               &lt;maxInclusive value="16777215"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="rttUnits-r16"&gt;
 *           &lt;simpleType&gt;
 *             &lt;union memberTypes=" {http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *                   &lt;enumeration value="microseconds"/&gt;
 *                   &lt;enumeration value="hundredsofnanoseconds"/&gt;
 *                   &lt;enumeration value="tensofnanoseconds"/&gt;
 *                   &lt;enumeration value="nanoseconds"/&gt;
 *                   &lt;enumeration value="tenthsofnanoseconds"/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *             &lt;/union&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="rttAccuracy-r16" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WLAN-RTT-r16Mapper", namespace = "", propOrder = {
    "rttValueR16",
    "rttUnitsR16",
    "rttAccuracyR16",
    "any"
})
public class WLANRTTR16Mapper {

    @XmlElement(name = "rttValue-r16")
    protected long rttValueR16;
    @XmlElement(name = "rttUnits-r16", required = true)
    protected String rttUnitsR16;
    @XmlElement(name = "rttAccuracy-r16")
    protected Short rttAccuracyR16;
    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the rttValueR16 property.
     * 
     */
    public long getRttValueR16() {
        return rttValueR16;
    }

    /**
     * Sets the value of the rttValueR16 property.
     * 
     */
    public void setRttValueR16(long value) {
        this.rttValueR16 = value;
    }

    /**
     * Gets the value of the rttUnitsR16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRttUnitsR16() {
        return rttUnitsR16;
    }

    /**
     * Sets the value of the rttUnitsR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRttUnitsR16(String value) {
        this.rttUnitsR16 = value;
    }

    /**
     * Gets the value of the rttAccuracyR16 property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getRttAccuracyR16() {
        return rttAccuracyR16;
    }

    /**
     * Sets the value of the rttAccuracyR16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setRttAccuracyR16(Short value) {
        this.rttAccuracyR16 = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
