# 
# NrTest pattern

# file open
id = 1
# heartbeat
id = 8
# CuCpTestEventEnm cu_cp_test_event_enm
id = 3001
# CuCpX2SgnbActivityNotification cu_cp_x2_sgnb_activity_notification
id = 3002
# CuCpNgPaging cu_cp_ng_paging
id = 3003
# CuCpRwrMobilityDecision cu_cp_rwr_mobility_decision
id = 3004
# CuCpRrcMeasurementReport cu_cp_rrc_measurement_report
id = 3005
# CuCpNgUeRadioCapabilityCheckRequest cu_cp_ng_ue_radio_capability_check_request
id = 3006
# CuCpNgUeRadioCapabilityCheckResponse cu_cp_ng_ue_radio_capability_check_response
id = 3007
# CuCpXnNgRanNodeConfigurationUpdateAcknowledge cu_cp_xn_ng_ran_node_configuration_update_acknowledge
id = 3008
# CuCpXnNgRanNodeConfigurationUpdateFailure cu_cp_xn_ng_ran_node_configuration_update_failure
id = 3009
# CuCpXnNgRanNodeConfigurationUpdate cu_cp_xn_ng_ran_node_configuration_update
id = 3010
# CuCpXnSetupFailure cu_cp_xn_setup_failure
id = 3011
# CuCpXnSetupRequest cu_cp_xn_setup_request
id = 3012
# CuCpXnSetupResponse cu_cp_xn_setup_response
id = 3013
# CuCpNgPduSessionResourceSetupRequest cu_cp_ng_pdu_session_resource_setup_request
id = 3014
# CuCpNgPduSessionResourceSetupResponse cu_cp_ng_pdu_session_resource_setup_response
id = 3015
# CuCpRrcSecurityModeCommand cu_cp_rrc_security_mode_command
id = 3016
# CuCpRrcSecurityModeComplete cu_cp_rrc_security_mode_complete
id = 3017
# CuCpRrcSecurityModeFailure cu_cp_rrc_security_mode_failure
id = 3018
# CuCpRrcReconfiguration cu_cp_rrc_reconfiguration
id = 3019
# CuCpRrcReconfigurationComplete cu_cp_rrc_reconfiguration_complete
id = 3020
# CuCpProcPduSessionResourceSetup cu_cp_proc_pdu_session_resource_setup
id = 3021
# CuCpProcInitialCtxtEstab cu_cp_proc_initial_ctxt_estab
id = 3022
# CuCpNgNasNonDeliveryIndication cu_cp_ng_nas_non_delivery_indication
id = 3023
# CuCpProcNgSigConnEstab cu_cp_proc_ng_sig_conn_estab
id = 3024
# CuCpNgDownlinkNasTransport cu_cp_ng_downlink_nas_transport
id = 3025
# CuCpNgErrorIndicationCommon cu_cp_ng_error_indication_common
id = 3026
# CuCpNgErrorIndicationDedicated cu_cp_ng_error_indication_dedicated
id = 3027
# CuCpNgInitialContextSetupFailure cu_cp_ng_initial_context_setup_failure
id = 3028
# CuCpNgInitialContextSetupRequest cu_cp_ng_initial_context_setup_request
id = 3029
# CuCpNgInitialContextSetupResponse cu_cp_ng_initial_context_setup_response
id = 3030
# CuCpNgInitialUeMessage cu_cp_ng_initial_ue_message
id = 3031
# CuCpNgReset cu_cp_ng_reset
id = 3032
# CuCpNgResetAcknowledge cu_cp_ng_reset_acknowledge
id = 3033
# CuCpNgUeContextReleaseCommand cu_cp_ng_ue_context_release_command
id = 3034
# CuCpNgUeContextReleaseComplete cu_cp_ng_ue_context_release_complete
id = 3035
# CuCpNgUeContextReleaseRequest cu_cp_ng_ue_context_release_request
id = 3036
# CuCpNgUeRadioCapabilityInfoIndication cu_cp_ng_ue_radio_capability_info_indication
id = 3037
# CuCpNgUplinkNasTransport cu_cp_ng_uplink_nas_transport
id = 3038
# CuCpRrcUeCapabilityEnquiry cu_cp_rrc_ue_capability_enquiry
id = 3039
# CuCpRrcUeCapabilityInformation cu_cp_rrc_ue_capability_information
id = 3040
# CuCpRrcDlInformationTransfer cu_cp_rrc_dl_information_transfer
id = 3041
# CuCpRrcUlInformationTransfer cu_cp_rrc_ul_information_transfer
id = 3042
# CuCpRrcReject cu_cp_rrc_reject
id = 3043
# CuCpRrcRelease cu_cp_rrc_release
id = 3044
# CuCpRrcSetup cu_cp_rrc_setup
id = 3045
# CuCpRrcSetupComplete cu_cp_rrc_setup_complete
id = 3046
# CuCpRrcSetupRequest cu_cp_rrc_setup_request
id = 3047
# CuCpProcRrcEstab cu_cp_proc_rrc_estab
id = 3048
# CuCpX2SgnbModificationRequestAcknowledge cu_cp_x2_sgnb_modification_request_acknowledge
id = 3049
# CuCpX2SgnbModificationRequestReject cu_cp_x2_sgnb_modification_request_reject
id = 3050
# CuCpX2SgnbModificationRequest cu_cp_x2_sgnb_modification_request
id = 3051
# CuCpProcX2SnInitiatedSgnbModification cu_cp_proc_x2_sn_initiated_sgnb_modification
id = 3053
# CuCpX2RrcTransfer cu_cp_x2_rrc_transfer
id = 3054
# CuCpProcUeCtxtRel cu_cp_proc_ue_ctxt_rel
id = 3055
# CuCpX2SecondaryRatDataUsageReport cu_cp_x2_secondary_rat_data_usage_report
id = 3056
# CuCpX2EndcConfigurationUpdate cu_cp_x2_endc_configuration_update
id = 3057
# CuCpX2EndcConfigurationUpdateAcknowledge cu_cp_x2_endc_configuration_update_acknowledge
id = 3058
# CuCpX2EndcConfigurationUpdateFailure cu_cp_x2_endc_configuration_update_failure
id = 3059
# CuCpX2EndcX2SetupFailure cu_cp_x2_endc_x2_setup_failure
id = 3060
# CuCpX2EndcX2SetupRequest cu_cp_x2_endc_x2_setup_request
id = 3061
# CuCpX2EndcX2SetupResponse cu_cp_x2_endc_x2_setup_response
id = 3062
# CuCpEndcMobilityEvaluation cu_cp_endc_mobility_evaluation
id = 3063
# CuCpProcX2SgnbAdditionPreparation cu_cp_proc_x2_sgnb_addition_preparation
id = 3065
# CuCpProcX2SgnbChange cu_cp_proc_x2_sgnb_change
id = 3066
# CuCpX2SgnbAdditionRequest cu_cp_x2_sgnb_addition_request
id = 3067
# CuCpX2SgnbAdditionRequestAcknowledge cu_cp_x2_sgnb_addition_request_acknowledge
id = 3068
# CuCpX2SgnbAdditionRequestReject cu_cp_x2_sgnb_addition_request_reject
id = 3069
# CuCpX2SgnbChangeConfirm cu_cp_x2_sgnb_change_confirm
id = 3070
# CuCpX2SgnbChangeRefuse cu_cp_x2_sgnb_change_refuse
id = 3071
# CuCpX2SgnbChangeRequired cu_cp_x2_sgnb_change_required
id = 3072
# CuCpProcEndcRelease cu_cp_proc_endc_release
id = 3073
# CuCpProcEndcSetup cu_cp_proc_endc_setup
id = 3074
# CuCpX2SgnbModificationConfirm cu_cp_x2_sgnb_modification_confirm
id = 3075
# CuCpX2SgnbModificationRefuse cu_cp_x2_sgnb_modification_refuse
id = 3076
# CuCpX2SgnbModificationRequired cu_cp_x2_sgnb_modification_required
id = 3077
# CuCpNgPduSessionResourceModifyRequest cu_cp_ng_pdu_session_resource_modify_request
id = 3078
# CuCpNgPduSessionResourceModifyResponse cu_cp_ng_pdu_session_resource_modify_response
id = 3079
# CuCpNgPduSessionResourceReleaseCommand cu_cp_ng_pdu_session_resource_release_command
id = 3080
# CuCpNgPduSessionResourceReleaseResponse cu_cp_ng_pdu_session_resource_release_response
id = 3081
# CuCpX2SgnbReconfigurationComplete cu_cp_x2_sgnb_reconfiguration_complete
id = 3082
# CuCpX2SgnbReleaseConfirm cu_cp_x2_sgnb_release_confirm
id = 3083
# CuCpX2SgnbReleaseRequest cu_cp_x2_sgnb_release_request
id = 3084
# CuCpX2SgnbReleaseRequestAcknowledge cu_cp_x2_sgnb_release_request_acknowledge
id = 3085
# CuCpX2SgnbReleaseRequired cu_cp_x2_sgnb_release_required
id = 3086
# CuCpX2SnStatusTransfer cu_cp_x2_sn_status_transfer
id = 3087
# CuCpX2UeContextRelease cu_cp_x2_ue_context_release
id = 3088
# CuCpProcPduSessionResourceModify cu_cp_proc_pdu_session_resource_modify
id = 3089
# CuCpNgRerouteNasRequest cu_cp_ng_reroute_nas_request
id = 3090
# CuCpProcPduSessionResourceRelease cu_cp_proc_pdu_session_resource_release
id = 3091
# CuCpNgDownlinkRanStatusTransfer cu_cp_ng_downlink_ran_status_transfer
id = 3092
# CuCpNgHandoverCancelAcknowledge cu_cp_ng_handover_cancel_acknowledge
id = 3093
# CuCpNgHandoverCancel cu_cp_ng_handover_cancel
id = 3094
# CuCpNgHandoverCommand cu_cp_ng_handover_command
id = 3095
# CuCpNgHandoverFailure cu_cp_ng_handover_failure
id = 3096
# CuCpNgHandoverNotify cu_cp_ng_handover_notify
id = 3097
# CuCpNgHandoverPreparationFailure cu_cp_ng_handover_preparation_failure
id = 3098
# CuCpNgHandoverRequestAcknowledge cu_cp_ng_handover_request_acknowledge
id = 3099
# CuCpNgHandoverRequest cu_cp_ng_handover_request
id = 3100
# CuCpNgHandoverRequired cu_cp_ng_handover_required
id = 3101
# CuCpNgUplinkRanStatusTransfer cu_cp_ng_uplink_ran_status_transfer
id = 3102
# CuCpProcNrHoExeOut cu_cp_proc_nr_ho_exe_out
id = 3103
# CuCpProcNrHoPrepOut cu_cp_proc_nr_ho_prep_out
id = 3104
# CuCpProcX2MnInitiatedSgnbModification cu_cp_proc_x2_mn_initiated_sgnb_modification
id = 3105
# CuCpX2EndcConfigurationTransfer cu_cp_x2_endc_configuration_transfer
id = 3106

