//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.04 at 03:31:19 PM IST 
//


package com.ericsson.s345g.etcm.autogen;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="single" type="{com.ericsson.schema.etcm}Empty"/>
 *           &lt;element name="pdf" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *           &lt;element ref="{com.ericsson.schema.etcm}pdfmap"/>
 *         &lt;/choice>
 *         &lt;element name="compressed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "single",
    "pdf",
    "pdfmap",
    "compressed"
})
@XmlRootElement(name = "countertype")
public class Countertype {

    protected Empty single;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger pdf;
    protected Pdfmap pdfmap;
    protected Boolean compressed;

    /**
     * Gets the value of the single property.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getSingle() {
        return single;
    }

    /**
     * Sets the value of the single property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     */
    public void setSingle(Empty value) {
        this.single = value;
    }

    /**
     * Gets the value of the pdf property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPdf() {
        return pdf;
    }

    /**
     * Sets the value of the pdf property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPdf(BigInteger value) {
        this.pdf = value;
    }

    /**
     * Gets the value of the pdfmap property.
     * 
     * @return
     *     possible object is
     *     {@link Pdfmap }
     *     
     */
    public Pdfmap getPdfmap() {
        return pdfmap;
    }

    /**
     * Sets the value of the pdfmap property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pdfmap }
     *     
     */
    public void setPdfmap(Pdfmap value) {
        this.pdfmap = value;
    }

    /**
     * Gets the value of the compressed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCompressed() {
        return compressed;
    }

    /**
     * Sets the value of the compressed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCompressed(Boolean value) {
        this.compressed = value;
    }

}
