//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.04 at 03:31:19 PM IST 
//


package com.ericsson.s345g.etcm.autogen;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{com.ericsson.schema.etcm}pref"/>
 *           &lt;element ref="{com.ericsson.schema.etcm}pmref"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element ref="{com.ericsson.schema.etcm}if"/>
 *           &lt;element ref="{com.ericsson.schema.etcm}incr"/>
 *           &lt;element ref="{com.ericsson.schema.etcm}set"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="loopvar" use="required" type="{com.ericsson.schema.etcm}JavaIdentifier" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pref",
    "pmref",
    "_if",
    "incr",
    "set"
})
@XmlRootElement(name = "foreach")
public class Foreach {

    protected String pref;
    protected String pmref;
    @XmlElement(name = "if")
    protected If _if;
    protected Incr incr;
    protected Set set;
    @XmlAttribute(name = "loopvar", required = true)
    protected String loopvar;

    /**
     * Gets the value of the pref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPref() {
        return pref;
    }

    /**
     * Sets the value of the pref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPref(String value) {
        this.pref = value;
    }

    /**
     * Gets the value of the pmref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmref() {
        return pmref;
    }

    /**
     * Sets the value of the pmref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmref(String value) {
        this.pmref = value;
    }

    /**
     * Gets the value of the if property.
     * 
     * @return
     *     possible object is
     *     {@link If }
     *     
     */
    public If getIf() {
        return _if;
    }

    /**
     * Sets the value of the if property.
     * 
     * @param value
     *     allowed object is
     *     {@link If }
     *     
     */
    public void setIf(If value) {
        this._if = value;
    }

    /**
     * Gets the value of the incr property.
     * 
     * @return
     *     possible object is
     *     {@link Incr }
     *     
     */
    public Incr getIncr() {
        return incr;
    }

    /**
     * Sets the value of the incr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Incr }
     *     
     */
    public void setIncr(Incr value) {
        this.incr = value;
    }

    /**
     * Gets the value of the set property.
     * 
     * @return
     *     possible object is
     *     {@link Set }
     *     
     */
    public Set getSet() {
        return set;
    }

    /**
     * Sets the value of the set property.
     * 
     * @param value
     *     allowed object is
     *     {@link Set }
     *     
     */
    public void setSet(Set value) {
        this.set = value;
    }

    /**
     * Gets the value of the loopvar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoopvar() {
        return loopvar;
    }

    /**
     * Sets the value of the loopvar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoopvar(String value) {
        this.loopvar = value;
    }

}
