//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.04 at 03:31:19 PM IST 
//


package com.ericsson.s345g.etcm.autogen;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FunctionName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FunctionName">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ts"/>
 *     &lt;enumeration value="duration"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FunctionName")
@XmlEnum
public enum FunctionName {

    @XmlEnumValue("ts")
    TS("ts"),
    @XmlEnumValue("duration")
    DURATION("duration");
    private final String value;

    FunctionName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FunctionName fromValue(String v) {
        for (FunctionName c: FunctionName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
