//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.04 at 03:31:19 PM IST 
//


package com.ericsson.s345g.etcm.autogen;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com.ericsson.schema.etcm}pref"/>
 *         &lt;group ref="{com.ericsson.schema.etcm}BooleanValueExpression"/>
 *       &lt;/sequence>
 *       &lt;attribute name="loopvar" use="required" type="{com.ericsson.schema.etcm}JavaIdentifier" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pref",
    "op"
})
@XmlRootElement(name = "ifany")
public class Ifany {

    @XmlElement(required = true)
    protected String pref;
    protected Op op;
    @XmlAttribute(name = "loopvar", required = true)
    protected String loopvar;

    /**
     * Gets the value of the pref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPref() {
        return pref;
    }

    /**
     * Sets the value of the pref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPref(String value) {
        this.pref = value;
    }

    /**
     * Gets the value of the op property.
     * 
     * @return
     *     possible object is
     *     {@link Op }
     *     
     */
    public Op getOp() {
        return op;
    }

    /**
     * Sets the value of the op property.
     * 
     * @param value
     *     allowed object is
     *     {@link Op }
     *     
     */
    public void setOp(Op value) {
        this.op = value;
    }

    /**
     * Gets the value of the loopvar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoopvar() {
        return loopvar;
    }

    /**
     * Sets the value of the loopvar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoopvar(String value) {
        this.loopvar = value;
    }

}
